### ISSUE TITLE
`rly version` requires to be executed in relayer directory

### ISSUE THREAD

**Issue by 1xCL** [cosmos/relayer#100]
Running `rly version` from $HOME throws
```
$ rly version
Error: open go.mod: no such file or directory
open go.mod: no such file or directory
```
But from the relayer directory, it works.
```
$ cd go/src/github.com/iqlusioninc/relayer/
$ rly version
version: 0.1.0-115-g03bef79
commit: 03bef79312ebd12485427a41f2192aca5f7737bb
cosmos-sdk: v0.34.4-0.20200417201027-11528d39594c
go: go1.14 linux/amd64
```

**Comment by jackzampolin** [comment]
This is an interesting bug! I will be sure to look into this as I would really like the SDK version to be included in this output, but the way I'm currently pulling it looks to be problematic.

**Comment by asmodat** [comment]
I encountered exactly the same bug as OP here, but while building a testnet environment using docker.

**Comment by jaybxyz** [comment]
I also encountered the same error message as I tried to print `relayer` version info outside of $RELAYER path. I found that [this code](https://github.com/iqlusioninc/relayer/blob/v0.3.0/cmd/version.go#L34) looks up `go.mod` file in the underlying directory.

**Comment by jackzampolin** [comment]
https://github.com/iqlusioninc/relayer/pull/221/commits/a89a705583ac9f3eea02ce7787f08be3df8a526e fixes this issue
