### ISSUE TITLE
Add ibctest case for allowlist/denylist

### ISSUE THREAD

**Issue by agouin** [cosmos/relayer#1003]
We are missing test coverage on e2e channel filters.

Would be nice to have a paths update command in the relayer that would allow changing the channel filter, and then add that to ibctest to add test cases for allowlist/denylist after linking a path.

**Comment by boojamya** [comment]
Linking: https://github.com/cosmos/relayer/issues/887

**Comment by agouin** [comment]
Closed by #1000
