### ISSUE TITLE
RPC error -32603 - Internal error: could not find results for height

### ISSUE THREAD

**Issue by gaia** [cosmos/relayer#1037]
![image](https://user-images.githubusercontent.com/87547/200046025-dba3392a-9d64-4ee0-8665-51533036fc68.png)

rly 2.1.2. keep getting these errors on every chain but the block info can be queried manually.

Mintscan shows only success TXs for the fee payer address

**Comment by agouin** [comment]
This is a benign warning. Sometimes the tendermint rpc reported latest height is not yet ready to be queried. The relayer immediately retries after these errors. The relayer does not proceed until it successfully receives the block.

There is a PR that will clean up these warnings here https://github.com/cosmos/relayer/pull/847, but it is not harming the performance of the relayer in a meaningful way
