### ISSUE TITLE
Insufficient fee

### ISSUE THREAD

**Issue by joshlopes** [cosmos/relayer#1049]
Apologies in advance if this issue is trivial and should have been picked from elsewhere but had this issue for a while now and reached out to Discord channels etc and none was able to give me the solution.

I'm getting this issue here:

> 2022-11-29T10:28:51.736409Z    error    Error sending messages    {"src_chain_id": "evmos_9001-2", "dst_chain_id": "osmosis-1", "src_client_id": "07-tendermint-0", "dst_client_id": "07-tendermint-1840", "messages": {"pkt_0_event_type": "acknowledge_packet", "pkt_0_src_chan": "channel-204", "pkt_0_src_port": "transfer", "pkt_0_dst_chan": "channel-0", "pkt_0_dst_port": "transfer", "pkt_0_data": "{\"amount\":\"30408397958824120000\",\"denom\":\"transfer/channel-204/aevmos\",\"receiver\":\"evmos133uledcjjh87jxvy2weachxypxnerhxs34fcx6\",\"sender\":\"osmo1skz5j2w4gz3k9z5nyzkx26cueel3kjjh8yzurw\"}"}, "error": "insufficient fee", "errorVerbose": "insufficient fee\ncosmossdk.io/errors.Wrap\n\t/home/tedcrypto/go/pkg/mod/cosmossdk.io/errors@v1.0.0-beta.7/errors.go:187\ncosmossdk.io/errors.ABCIError\n\t/home/tedcrypto/go/pkg/mod/cosmossdk.io/errors@v1.0.0-beta.7/errors.go:75\ngithub.com/strangelove-ventures/lens/client.broadcastTx\n\t/home/tedcrypto/go/pkg/mod/github.com/strangelove-ventures/lens@v0.5.2-0.20220822201013-1e7ffd450f20/client/broadcast.go:86\ngithub.com/strangelove-ventures/lens/client.(*ChainClient).BroadcastTx\n\t/home/tedcrypto/go/pkg/mod/github.com/strangelove-ventures/lens@v0.5.2-0.20220822201013-1e7ffd450f20/client/broadcast.go:36\ngithub.com/cosmos/relayer/v2/relayer/chains/cosmos.(*CosmosProvider).SendMessages.func1\n\t/home/tedcrypto/relayer/relayer/chains/cosmos/tx.go:147\ngithub.com/avast/retry-go/v4.Do\n\t/home/tedcrypto/go/pkg/mod/github.com/avast/retry-go/v4@v4.1.0/retry.go:122\ngithub.com/cosmos/relayer/v2/relayer/chains/cosmos.(*CosmosProvider).SendMessages\n\t/home/tedcrypto/relayer/relayer/chains/cosmos/tx.go:77\ngithub.com/cosmos/relayer/v2/relayer/processor.(*PathProcessor).sendMessages\n\t/home/tedcrypto/relayer/relayer/processor/path_processor_internal.go:751\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1571"}

This is the configuration:

```
    evmos:
        type: cosmos
        value:
            key: tedrelayer
            chain-id: evmos_9001-2
            rpc-addr: http//localhost:26657
            account-prefix: evmos
            keyring-backend: test
            gas-adjustment: 1.3
            gas-prices: 20000000000aevmos
            min-gas-amount: 1
            debug: false
            timeout: 20s
            output-format: json
            sign-mode: direct
```

Not sure what else I need to do. Tired to add `0` to gas-price and min-gas-amount but no luck.

**Comment by joeabbey** [comment]
@joshlopes which version of relayer are you running?

**Comment by joshlopes** [comment]
@joeabbey 

```
tedcrypto@tedrelayer  ~ rly version
version: 2.1.2
commit: unknown
cosmos-sdk: v0.46.0
go: go1.18.2 linux/amd64
```

This is the wallet: https://www.mintscan.io/evmos/account/evmos1lzw67hwyslyxdwl4sv3rl78xvv096vzsmr27j4 it worked one time I think ?

**Comment by joeabbey** [comment]
I assume this is just copy pasta error, but your rpc in the above config is: `            rpc-addr: http//localhost:26657`

**Comment by joeabbey** [comment]
I was able to replicate this by setting a minimum-gas-price that was higher in `~/.evmosd/config/app.toml` than was set in `~/.relayer/config/config.toml`

e.g.

in `~/.evmosd/config/app.toml` this worked:

```
minimum-gas-prices = "20000000000aevmos"
```

while this failed with insufficient fee

```
minimum-gas-prices = "21000000000aevmos"
```

Have you checked your `~/.evmosd/config/app.toml`?

**Comment by boojamya** [comment]
Closing. Stale.

**Comment by joshlopes** [comment]
@joeabbey was investigating not sure if he found anything @boojamya but is still an issue :)
