### ISSUE TITLE
[Bug]identifier cannot be blank

### ISSUE THREAD

**Issue by ItsFunny** [cosmos/relayer#1059]
# Background 
Try to create channel between localnetowrk with secret-network
command: rly tx link test_sec --src-port transfer --dst-port transfer --order unordered --version ics20-1  -d --override

# Problem
It will be failed when calls `Chain#CreateOpenChannels# ValidateConnectionPaths`

**Comment by boojamya** [comment]
Is it possible provide a stack trace?
