### ISSUE TITLE
rc3 breaks coin-type 60 keys

### ISSUE THREAD

**Issue by ghost** [cosmos/relayer#1066]
The newest release breaks coin-type 60. I use the key with Evmos, and it works fine for rc2 and below. However, upon upgrading, attempting to start the relayer will give the following error:
```
Error: key evmos_key not found on chain evmos_9001-2
```

Even restoring from the seed with `--coin-type 60` doesn't change anything. I see that the key is correctly generated and placed in `/keys/keyring-test`, so I'm not sure what the issue is.

**Comment by alkadeta** [comment]
Hey @ivaldilabs, you can get rid of this error by adding `extra-codecs: [ethermint]` or `extra-codecs: [injective]` to your config.yaml file.

**Comment by ghost** [comment]
Thanks, that did it indeed!
