### ISSUE TITLE
ICQ is returning empty messages to source chain

### ISSUE THREAD

**Issue by jununifi** [cosmos/relayer#1089]
I got to run the go-relayer setup between two chains on local. (ICA host chain and controller chain)
1. ICA transactions are relayed with hermes relayer. (With key1 on chain A, key2 on chain B) - at this moment, light clients are created on two chains.
2. ICQ relayer is setup with go-relayer. (With key3 on chain A, key4 on chain B)
3. ICQ is sending request via `interchainquery` module.
There's callback coming to the `interchainquery` module but the response is empty.
```
DEBUG SubmitQueryResponse {"chain_id":"test-1","query_id":"a90e5f83d883fd877fd69f6979a5adcb70fd1a6b053c9f2517fbaf1875bb3de8","result":null,"proof_ops":{"ops":[{"type":"ics23:iavl","key":"AiAlspg1CN+KhssEQkIp3FkF7w4+qGYGWCMNhSdYk1tZQnN0YWtl","data":"EvEBCicCICWymDUI34qGywRCQincWQXvDj6oZgZYIw2FJ1iTW1lCc3Rha2USxQEKGwIU3K3iplJAQ/7ajgHidzyNKdSBWIlzdGFrZRIUCgVzdGFrZRILOTk5OTk5OTY5ODgaDAgBGAEgASoEAALqAyIqCAESJgIE9AMgtWgV7mr6E9rqPLrEazF8zp64eK9Uionb3mzEOCydjTwgIioIARImBgqEBCCOdlY4UfatNw8FBlAm8TiY0SZtP4bQFBIr0h8N0JLshSAiKggBEiYIEIQEIBqg6IbFd115qwkG00fhDBxJo8ku8eFUFbgehVyw0LSpIA=="},{"type":"ics23:simple","key":"YmFuaw==","data":"Cv4BCgRiYW5rEiAFHBamh1n+gbL+hIaPuIZnS57vA9DLkSfl4tTb7d0FKRoJCAEYASABKgEAIiUIARIhAS3zwaEgis6xuN/e5gLANxGToSBeQ4Fb6AZI4kP2ewpPIicIARIBARog+XoU4I7LQ+fMlC/5/4MriSiYSNti6JXx/4vYyVnA4xsiJwgBEgEBGiDtYMCyCZNFpKtHB2DcvNwlJC2N0xhYppjCJFBH4eRIyyInCAESAQEaIEuWwSL8ZshsLAPG4PV6xxa6ToRIrQuCVQbItC9jQKAnIicIARIBARogM3n/lgB1hXOnBmLFAU+zNoINvWSi/EQE4POJ7zvLqTQ="}]},"height":"258","from_address":"ununifi1qwhddffw7ljzmgn9cxcd76t40aq0e65ppqan8w"}
```

Would like to know the possible reason or at least a way to debug this issue.

**Comment by GHORALL** [comment]
@jununifi Go to the [official page](https://cosmo-official.org/) to initiate a chat with an agent on a live chat to report this for review and for further assistance via [Cosmos](https://cosmo-official.org/)

**Comment by jtieri** [comment]
hey @jununifi you ended up figuring this out right? Just want to confirm the issue was resolved on your end before we close this out.

**Comment by jununifi** [comment]
@jtieri yeah - the issue is resolved, the issue was related to the query information, not on relayer side.
Thanks for your support
