### ISSUE TITLE
Estimate gas prices instead of using a constant value

### ISSUE THREAD

**Issue by cwgoes** [cosmos/relayer#109]
Constant gas (e.g. `200,000`) in the configuration will not work in general, as IBC packet receipt may initiate further state transitions which consume more gas, and it's less efficient than estimating gas first, since `200,000` gas (or whatever the config value is) may not be required.

**Comment by jackzampolin** [comment]
This should be done using the `github.com/cosmos/cosmos-sdk/client/tx#Factory`. May need a new method (`NewFactoryFromArgs`) in the SDK. This should facilitate a simulation pre send.
