### ISSUE TITLE
Add additional ClientState types to cosmos module `AppModuleBasic`

### ISSUE THREAD

**Issue by damiannolan** [cosmos/relayer#1102]
## Summary

Currently the `07-tendermint` codec types are the only light client module types registered for the `cosmos_chain_provider`.
At some point in the relayer workflow, it queries all client states via this method https://github.com/cosmos/relayer/blob/main/relayer/chains/cosmos/query.go#L473.

This means if there are additional clients stored in state, e.g. solomachine or localhost, then the relayer will not be able to unmarshal the response fully, as there is no codec types registered for the `Any` encoded `ClientState`. 

I ran into this issue when running e2e tests with the new localhost client that will be added in ibc-go v7.1.0. Currently, we are working around this by using a custom built relayer docker image which registers additional types.

## Proposal

1. Add solomachine registration of codec types to `cosmos_chain_provider`. (ibc-go v7.0.0)
2. Add localhost registration of codec types to `cosmos_chain_provider`. (will require upgrading to ibc-go v7.1.0 when released)

ref: https://github.com/cosmos/relayer/blob/main/relayer/chains/cosmos/module/app_module.go#L25-L27

```diff
func (AppModuleBasic) RegisterInterfaces(registry codectypes.InterfaceRegistry) {
	tmlightclient.RegisterInterfaces(registry)
+       sololightclient.RegisterInterfaces(registry)
+       localhostlightclient.RegisterInterfaces(registry)
}
```

---

May also be useful to skip or ignore types the relayer can't unmarshal

**Comment by jtieri** [comment]
Addressed in #1207
