### ISSUE TITLE
Explore consolidating broadcasting logic

### ISSUE THREAD

**Issue by jtieri** [cosmos/relayer#1108]
Now the we have removed `lens` as a dependency and all the broadcasting logic lives in the relayer, there may be some room for improving/consolidating some of that code. 

Mostly opening this issue as a reminder to look into this later

**Comment by jonathanpberger** [comment]
Initial implementation done, waiting on `feeGrant` work w/ @KyleMoser so we don't have conflicts.

**Comment by jonathanpberger** [comment]
@joeabbey will break this story down to more granular pieces
