### ISSUE TITLE
Bootstrap light clients from already-trusted chains

### ISSUE THREAD

**Issue by cwgoes** [cosmos/relayer#111]
Let's say I've already set up a light client for chain `Alpha`, and chain `Alpha` has *IBC* light clients (i.e. in state) for chains `Bravo` and `Charlie`. Since I can verify state on `Alpha`, I should be able to pull the data (configuration, consensus state, unbonding period, etc.) from the on-chain clients to setup local clients for `Bravo` and `Charlie` - then I can relay between all three chains.

**Comment by jackzampolin** [comment]
This would be a really cool feature! The `./four-chainz` script is a good starting point for any developer would like to build out this feature~
