### ISSUE TITLE
Misbehaviour monitoring & relay

### ISSUE THREAD

**Issue by cwgoes** [cosmos/relayer#112]
Given a particular configuration option, using the local light clients, the relayer should periodically check if any conflicting (equivocating) headers have been submitted to any on-chain IBC light clients on the chains which are being monitored (relayed between), and if they have, the relayer should automatically submit proof-of-misbehaviour to freeze the on-chain light clients (and print a very scary red warning message encouraging the user to immediately investigate).

**Comment by jackzampolin** [comment]
This is blocked on https://github.com/cosmos/relayer/pull/324

**Comment by colin-axner** [comment]
tagging for akash

This is an essential feature requirement for the relayer. It requires a bit of work and definitely should wait until typed events are added. Might not be the best first issues to pickup, but definitely something that should be prioritized. Checkout [07-tendermint](https://github.com/cosmos/cosmos-sdk/tree/master/x/ibc/light-clients/07-tendermint/types) to understand how misbehaviour is formed and handled. 

cc @gosuri @anilCSE @akhilkumarpilli @boz

**Comment by colin-axner** [comment]
Here's how this should be done:

When an update client event occurs while listening to streaming events, parse the header out of the emitted events. Check that header against the trusted headers in the light client store. If they match, do nothing and move on. If they don't match. Construct a misbehaviour and submit it to the on-chain client
