### ISSUE TITLE
Support multiple kinds of light clients

### ISSUE THREAD

**Issue by cwgoes** [cosmos/relayer#113]
As far as I can tell, right now, the relayer just support Tendermint light clients (ICS 7).

We should update the code to deal with clients more generically, and we should be able to support loop-back clients ([spec](https://github.com/cosmos/ics/tree/master/spec/ics-009-loopback-client), [implementation](https://github.com/cosmos/cosmos-sdk/pull/6018)) now, and other types (e.g. GRANDPA) later.

What does it mean to support a solo machine client? Does it have to provide an HTTP API? What does Agoric think / what do they need?

**Comment by jackzampolin** [comment]
I think the first step here is adding the client type to the `Chain` struct and then using that.

**Comment by jackzampolin** [comment]
Relayer now supports multiple types of light clients (solochain, localhost, tendermint)
