### ISSUE TITLE
look into http response and provide more understandable logs when a node is inaccessible

### ISSUE THREAD

**Issue by jtieri** [cosmos/relayer#1136]
If an operator is running against a node that has rate limiting etc. enforced it is possible that the relayer will suddenly start spitting out unmarshaling errors like the following:

```
2023-03-22T10:44:43.024612Z     warn    Error querying block data       {"chain_name": "osmo-test-4", "chain_id": "osmo-test-4", "error": "error unmarshalling: invalid character '<' looking for beginning of value"}
```

we should inspect the http response and attempt to provide a more understandable error message

**Comment by joelsmith-2019** [comment]
This issue cannot be reproduced as CometBFT improved their error messages. [CometBFT PR 638](https://github.com/cometbft/cometbft/pull/638)

## New Error Output

It will now output errors like so:

`2024-06-13T21:57:54.509264Z     error   Failed to query node status     {"chain_name": "cosmoshub", "chain_id": "cosmoshub-4", "attempt": 1, "max_attempts": 5, "error": "failed to query node status: error in json rpc client, with http response metadata: (Status: 429 Too Many Requests, Protocol HTTP/1.1). error unmarshalling: invalid character '<' looking for beginning of value"}`

`2024-06-13T21:57:41.272102Z     error   Failed to check for misbehaviour        {"path_name": "cosmoshub-osmosis", "chain_id": "osmosis-1", "client_id": "07-tendermint-1", "client_id": "07-tendermint-1", "error": "error in json rpc client, with http response metadata: (Status: 429 Too Many Requests, Protocol HTTP/1.1). error unmarshalling: invalid character '<' looking for beginning of value"}`

@jtieri, we should be able to mark this issue as closed
