### ISSUE TITLE
rly tx link demo , i am get error

### ISSUE THREAD

**Issue by 0mustafasevinc0** [cosmos/relayer#116]
I cannot perform operations of "https://github.com/iqlusioninc/relayer". I'm getting an error. Where am I making mistakes.

root@cb520bd2d4e2:~# rly tx link demo      
I[2020-04-21|14:59:27.222] ✘ [ibc0]@{0} - msg(0:create_client) err(sdk: tx parse error) 
I[2020-04-21|14:59:27.241] ✘ [ibc1]@{0} - msg(0:create_client) err(sdk: tx parse error) 
I[2020-04-21|14:59:28.152] ✘ [ibc0]@{29406} - msg(0:channel_open_init) err(connection: connection not found) 
I[2020-04-21|14:59:37.558] ✘ [ibc0]@{29415} - msg(0:channel_open_init) err(connection: connection not found) 
I[2020-04-21|14:59:47.950] ✘ [ibc0]@{29425} - msg(0:channel_open_init) err(connection: connection not found) 
E[2020-04-21|14:59:47.950] ibc0: err(! Channel failed: [ibc0]chan{ibconexfer}port{transfer} -> [ibc1]chan{ibczeroxfer}port{transfer})

**Comment by xyz2020** [comment]
me too

**Comment by 0mustafasevinc0** [comment]
It works only in these versions.For now new versions are not working. You can go to older versions by saying "git checkout <commit-hash>".

Gaia Version Info
$ gaiad version --long
name: gaia
server_name: gaiad
client_name: gaiacli
version: 0.0.0-303-g9a09e54
commit: 9a09e5499c25f8bbe48f2f9abe6f74360923266b
build_tags: netgo,ledger
go: go version go1.14 darwin/amd64
Relayer Version Info
$ rly version
version: 0.2.0
commit: 49e0d7316410b480236e280b0d94731adc807383
cosmos-sdk: v0.34.4-0.20200419154345-84774907316c
go: go1.14 darwin/amd64
