### ISSUE TITLE
Avalanche Tasks

### ISSUE THREAD

**Issue by KyleMoser** [cosmos/relayer#1166]
WIP: Define scope of Avalanche integration effort.

- Interaction w/ Avalanche chain
- Provider implementation for Avalanche
- Creating connections, channels
- Token transfers
- Test case in ibctest

1. Implement processor.ChainProcessor interface
2. Implement provider.ChainProvider interface
    - Implement avalanche ChainProcessor functions: queryCycle, CollectMetrics, handleMessage, ibcMessagesFromBlockEvents 
    -  Note: for some, e.g. ibcMessagesFromBlockEvents, there may not be a 1:1 function for Avalanche. Conceptually, the main queryCycle loop and its function calls will be needed for Avalanche.
3. Implement KeyProvider
4. Implement ProviderConfig

Note that as similar work is being completed in interchaintest, the relayer implementation will lag slightly behind interchaintest for certain features (e.g. KeyProvider which is also in interchaintest).

**Comment by jonathanpberger** [comment]
Waiting to implement e2e tests.

**Comment by akc2267** [comment]
want to start with connectionopeninit and connectionopentrie
