### ISSUE TITLE
Remove "replace" statement once FeeGrant is merged

### ISSUE THREAD

**Issue by boojamya** [cosmos/relayer#1167]
In `go.mod` remove:

`replace github.com/cosmos/cosmos-sdk => github.com/KyleMoser/cosmos-sdk v0.47.0-cachefix`

Once this is merged: https://github.com/cosmos/relayer/pull/1140

**Comment by KyleMoser** [comment]
FYI I updated the PR to SDK v0.47.2 since it was backported.

**Comment by akc2267** [comment]
done!
