### ISSUE TITLE
Multiple keys delete from a single command

### ISSUE THREAD

**Issue by Cosmos-Harry** [cosmos/relayer#1188]
Would be nice to have a flag in `rly keys delete` that delete all the keys and/or keys with the same keyname in all the chains.

**Comment by jonathanpberger** [comment]
This work is captured in #1193

**Comment by akc2267** [comment]
from our end, we are unsure if this is a feature we want to support. There are concerns with accidentally deleting all keys

**Comment by reecepbcups** [comment]
closing as stale
