### ISSUE TITLE
Relayer does not auto forward packets on SDK v0.47.2

### ISSUE THREAD

**Issue by reecepbcups** [cosmos/relayer#1195]
These instead have to be manually flushed to push through.

When manually Flushing, the packets deliver as expected as seen here. (Removing the flush line breaks the test)
https://github.com/CosmosContracts/juno/blob/47-upgrade/interchaintest/ibc_transfer_test.go#L130-L143

Current test uses ibc-go-simd on SDK v47-rc1. Something between this and v0.47.2 may have broken it. It works successfully with hermes on 1.4.1

**Comment by jonathanpberger** [comment]
We'll revisit on v0.47.3.

**Comment by jonathanpberger** [comment]
Should get fixed by https://github.com/cosmos/relayer/pull/1221

**Comment by reecepbcups** [comment]
Thank you! Works now as intended :partying_face:
