### ISSUE TITLE
Export wallet address for prometheus metrics

### ISSUE THREAD

**Issue by DavidNix** [cosmos/relayer#1203]
Perhaps another label on this metric.

![image (5)](https://github.com/cosmos/relayer/assets/224251/d50f9d60-8f4a-4798-839a-38bcace93b4f)

This allows us to show the address in alerts and/or on dashboards. Prevents someone from hunting down the address and possibly finding an incorrect one.

E.g. `address="somm1kn4tkqezr3c7zc43lsu5r4p2l2qqf4mpatu7vv"`

**Comment by jtieri** [comment]
Looks like this was just addressed with #1206 so i'm going to close this out. Feel free to open it back up if something was missed.
