### ISSUE TITLE
Relayer should check for counterparty ibc client consensus height before relaying packets

### ISSUE THREAD

**Issue by omritoptix** [cosmos/relayer#1220]
Not sure if this is not the intended behavior or just a bug but I wonder why doesn't the relayer waits for the counter party consensus height to be greater then the relayed packet height before trying to send it.

As a result of trying to send while `packet height < counter party ibc client consensus height`, the relayer gives up on the packet at some point. 

AFAIU the relevant piece of code should reside in this func:

```
// shouldSendPacketMessage determines if the packet flow message should be sent now.
// It will also determine if the message needs to be given up on entirely and remove retention if so.
func (pathEnd *pathEndRuntime) shouldSendPacketMessage(message packetIBCMessage, counterparty *pathEndRuntime) bool {
```

**Comment by jtieri** [comment]
every packet in the relayer _should_ be sent with a `MsgUpdateClient` preceding it if necessary so if a packet is sent at block height 100 and the counterparty's light client tracking the source chain was last updated with a client state from block height 80 the relayer will compose a `MsgUpdateClient` and send that msg with the packet in the same tx

https://github.com/cosmos/relayer/blob/892e52cc41b6092ff32be4a49e67ccefc954729a/relayer/processor/message_processor.go#L96-L107
