### ISSUE TITLE
Relayer support for liquid staking module

### ISSUE THREAD

**Issue by sampocs** [cosmos/relayer#1237]
Gaia will be upgrading soon to add the liquid staking module ([context](https://www.mintscan.io/cosmos/proposals/790)). This manifests itself in changes to the core SDK staking and distribution module's, and will live on a new SDK branch ([v0.45.16-ics-lsm](https://github.com/cosmos/cosmos-sdk/pull/16747)).

Since new parameters were added to the staking module, I believe queries in the relayer for the unbonding time and trusting period will fail ([here](https://github.com/cosmos/relayer/blob/main/relayer/chains/cosmos/provider.go#L178-L192) and [here](https://github.com/cosmos/relayer/blob/main/relayer/chains/cosmos/query.go#L247-L264)).

As far as the timeline goes, I think gaia is a few weeks out from having this on mainnet, but the testnet should be up in the next couple days, so the sooner the better!

I'll leave it to y'all to figure out the best way to resolve and test this. But if you're interested, here's a version of gaia with LSM support that I'd imagine you could easily use with ibctesting to verify: https://github.com/Stride-Labs/gaia/tree/v10.0.2-lsm-debug-v4

**Comment by akc2267** [comment]
https://github.com/strangelove-ventures/interchaintest/commit/f2cc74d073a7b4869516ba5781669773bf5a19d9

**Comment by akc2267** [comment]
from @vimystic :

CP : 385 : was pulled in from v3 to v4 .
https://github.com/strangelove-ventures/interchaintest/commit/ba9d3221437eb65b330bdca8450b88530e11c17b


Same CP: attempting to pull from v4 to v7.
https://github.com/strangelove-ventures/interchaintest/commit/f2cc74d073a7b4869516ba5781669773bf5a19d9


Package Changes: 
ibc-go :  v4 to v7
Interchain-security : v2.0.0 to v3.1.0
cosmos sdk : 0.45.15 to 0.47 
tendermint 0.37 :  cometbft 0.37

**Comment by sampocs** [comment]
The RC was just created this morning if you want to test with that: https://github.com/cosmos/cosmos-sdk/releases/tag/v0.45.16-ics-lsm-rc0

**Comment by jtieri** [comment]
We believe this is not an issue anymore and that the relayer is working fine on these newer versions of Stride/Cosmos Hub. Going to close this issue out, feel free to re-open if necessary!
