### ISSUE TITLE
Error when initializing the chain on the local setup

### ISSUE THREAD

**Issue by daluxxx** [cosmos/relayer#124]
The server setup works like a charm for me. However, when I do the local setup on a standalone server, I get the following error when initializing the lite client for mychainid:

rly lite init mychainid -f
Error: only one witness left. please reset the light client
only one witness left. please reset the light client

I also reinstalled both machines, and again the same error. Base system is Ubuntu 18.04.

rly version
version: 0.2.1-4-ge655713
commit: e655713b8bcd5bb349fb6ea6924bc270532b7a5d
cosmos-sdk: v0.34.4-0.20200419154345-84774907316c
go: go1.14 linux/amd64

After rly lite delete mychainid, still the same error when initializing.

**Comment by daluxxx** [comment]
I found the issue for the problem:

When there is the string "stake" in the CHAINID, then the command sed -i "s/stake/$DENOM/g" ~/.gaiad/config/genesis.json is not working properly, because in the genesis.json the a wrong chainid is inputted. When I then manually change the chainid in the genesis.json, everything is working fine.

**Comment by jackzampolin** [comment]
@daluxxx you need to update to `v0.3.0` of the relayer and `gaiad` version should match that here: https://github.com/iqlusioninc/relayer/tree/master/testnets

**Comment by daluxxx** [comment]
I updated to the newest version v0.3.0 and the problem is still there. When there is the word "stake" in the $CHAINID, then the command "sed -i "s/stake/$DENOM/g" ~/.gaiad/config/genesis.json" is generating a wrong chainid in the genesis.json file.

**Comment by jackzampolin** [comment]
closed by #147
