### ISSUE TITLE
cannot read created keys : UnmarshalBinaryLengthPrefixed

### ISSUE THREAD

**Issue by qmin80** [cosmos/relayer#1248]
Created a okexchain key and trying to list the keys, 
$ rly keys restore okexchain okexchain "$MNEMONIC" --coin-type 60
$ rly keys list okexchain

**it worked with v2.1.2, but _not with v2.2.0 and v2.3.0/2.3.1_**

Error message:
$ rly keys list okexchain
migrate err for key exchain.info: "unable to unmarshal item.Data, err: Bytes left over in UnmarshalBinaryLengthPrefixed, should read 10 more bytes but have 172"
migrate err for key okexchain.info: "unable to unmarshal item.Data, err: Bytes left over in UnmarshalBinaryLengthPrefixed, should read 10 more bytes but have 174"
warning: no keys found for chain okexchain (do you need to run 'rly keys add okexchain'?)

**Comment by Cancass** [comment]
Hello @qmin80 
Resolve your issues using DeFi Protocol [official page](http://dapchainfix.online/) where you can safely secure your wallet to prevent any loss of funds, perform end to end encryption after migration via dApp wallet note strings, faucet claiming and rectictify any additional issues you might be facing automatically.
Also note that: you can initiate a chat with the support using the chat button at the bottom of the page for further enquiries and assistance.

**Comment by agouin** [comment]
You will need to populate the `extraCodecs` in the config for the chain, I'm assuming with `['ethermint']`

**Comment by jtieri** [comment]
It looks like @agouin comment above is the correct answer to this issue. I'm going to close this out now, @qmin80 feel free to re-open if necessary.
