### ISSUE TITLE
execute "systemctl status gaiad" failed 

### ISSUE THREAD

**Issue by wangfeiping** [cosmos/relayer#126]
CentOS Linux release 7.7.1908 (Core)

rly version
version: 0.3.0-1-g5879ef9
commit: 5879ef9375f7422c4aed677c5b7c22b94058ad18
cosmos-sdk: v0.34.4-0.20200423152229-f1fdde5d1b18
go: go1.14.1 linux/amd64

gaiad version --long
name: gaia
server_name: gaiad
client_name: gaiacli
version: 0.0.0-333-gd26d6ed
commit: d26d6eddcf8dbb87ed101f69419e3b79cdb568c6
build_tags: netgo,ledger
go: go version go1.14.1 linux/amd64

I try to join the testnet,

Everything looks like ok in Server Setup,
but when I execute "systemctl status gaiad", I get failed.

● gaiad.service - gaiad
   Loaded: loaded (/etc/systemd/system/gaiad.service; disabled; vendor preset: disabled)
   Active: activating (auto-restart) (Result: exit-code) since 五 2020-04-24 14:54:19 CST; 1s ago
  Process: 602 ExecStart=/root/go/bin/gaiad start --pruning=nothing (code=exited, status=1/FAILURE)
 Main PID: 602 (code=exited, status=1/FAILURE)

4月 24 14:54:19 iZ6we0wdz6sdpueno5relzZ systemd[1]: gaiad.service: main process exited, code=exited, status=1/FAILURE
4月 24 14:54:19 iZ6we0wdz6sdpueno5relzZ systemd[1]: Unit gaiad.service entered failed state.
4月 24 14:54:19 iZ6we0wdz6sdpueno5relzZ systemd[1]: gaiad.service failed.

I try to execute "/root/go/bin/gaiad start --pruning=nothing",
Then I get:

I[2020-04-24|14:54:31.421] starting ABCI with Tendermint                module=main 
ERROR: error during handshake: error on replay: validator set is nil in genesis and still empty after InitChain

Do I do something wrong?

**Comment by wangfeiping** [comment]
I changed version of gaia, but still failed.

name: gaia
server_name: gaiad
client_name: gaiacli
version: 0.0.0-180-g50be36d
commit: 50be36de941b9410a4b06ec9ce4288b1529c4bd4
build_tags: netgo,ledger
go: go version go1.14.1 linux/amd64

$ vi /root/.gaiad/config/genesis.json
```
...
"app_state": {
    "evidence": {
      "evidence": []
    },
    "staking": {
      "params": {
        "unbonding_time": "1814400000000000",
        "max_validators": 100,
        "max_entries": 7,
        "historical_entries": 100,
        "bond_denom": "dawns"
      },
      "last_total_power": "0",
      "last_validator_powers": null,
      "validators": null,
      "delegations": null,
      "unbonding_delegations": null,
      "redelegations": null,
      "exported": false
    },
...
```

**Comment by wangfeiping** [comment]
After re-setup 5-6 times,
delete the relayer repo: $GOPATH/src/github.com/iqlusioninc/relayer;
delete the relayer data path: /root/.relayer/;
delete the data path: /root/.gaiad/;
restart the server;

gaiad is running.

I don't really know what happened.

**Comment by jackzampolin** [comment]
Thank you for the update here @wangfeiping! Glad you were able to get everything working.
