### ISSUE TITLE
upgrade to ibc v8

### ISSUE THREAD

**Issue by akc2267** [cosmos/relayer#1266]

**Comment by conorsch** [comment]
Penumbra recently moved to ibc v8 https://github.com/penumbra-zone/penumbra/pull/3016, to match what's in `interchaintest`. It'd be great to see `relayer` move as well. Until then, we're blocked from updating our proto definitions in the relayer repo.

**Comment by jtieri** [comment]
Closed by #1312 

**_huge_** shoutout to @faddat who had started working on upgrading these dependencies and making the necessary adjustments throughout the repo in separate PRs
