### ISSUE TITLE
BlockResults rpc has changed in comet v0.38 update

### ISSUE THREAD

**Issue by colin-axner** [cosmos/relayer#1273]
v0.34.X [Block Results RPC](https://github.com/cometbft/cometbft/blob/v0.34.29/rpc/core/types/responses.go#L49):
```go
// ABCI results from a block
type ResultBlockResults struct {
	Height                int64                     `json:"height"`
	TxsResults            []*abci.ResponseDeliverTx `json:"txs_results"`
	BeginBlockEvents      []abci.Event              `json:"begin_block_events"`
	EndBlockEvents        []abci.Event              `json:"end_block_events"`
	ValidatorUpdates      []abci.ValidatorUpdate    `json:"validator_updates"`
	ConsensusParamUpdates *abci.ConsensusParams     `json:"consensus_param_updates"`
}
```

v0.38.X [Block Results RPC](https://github.com/cometbft/cometbft/blob/v0.38.0-rc3/rpc/core/types/responses.go):
```go
// ABCI results from a block
type ResultBlockResults struct {
	Height                int64                     `json:"height"`
	TxsResults            []*abci.ExecTxResult      `json:"txs_results"`
	FinalizeBlockEvents   []abci.Event              `json:"finalize_block_events"`
	ValidatorUpdates      []abci.ValidatorUpdate    `json:"validator_updates"`
	ConsensusParamUpdates *cmtproto.ConsensusParams `json:"consensus_param_updates"`
	AppHash               []byte                    `json:"app_hash"`
}
```

The relayer currently looks for begin and end blocks [here](https://github.com/cosmos/relayer/blob/main/relayer/chains/cosmos/cosmos_chain_processor.go#L448) after performing this [rpc query](https://github.com/cosmos/relayer/blob/main/relayer/chains/cosmos/cosmos_chain_processor.go#L390)

This results in no begin/end block results for chains on SDK v0.50

Begin/End block event parsing is needed for interchain accounts integration with gov/groups SDK modules

**Comment by jtieri** [comment]
This was addressed in #1312 by maintaining a fork of `cometbft` before `v0.38.0` and importing that fork as well. It seems like `cometbft` will soon have a stable `v1.0.0` release, at that point we should be able to drop the fork entirely as well.
