### ISSUE TITLE
Creating a Channel with different ports creates new connection

### ISSUE THREAD

**Issue by ertemann** [cosmos/relayer#1320]
1. Channel existed between Secret and Archway

{"chain_id":"secret-4","channel_id":"channel-84","client_id":"07-tendermint-169","connection_hops":["connection-119"],"counterparty":{"chain_id":"archway-1","channel_id":"channel-21","client_id":"07-tendermint-24","connection_id":"connection-22","port_id":"transfer"}

2. made a new channel using 

` rly paths new archway-1 secret-4 archway-secretnetwork_snip
rly tx connect archway-secretnetwork_snip --src-port transfer --dst-port wasm.secret1tqmms5awftpuhalcv5h5mg76fa0tkdz4jv9ex4 --order unordered --version ics20-1

3.  checked that it used the existing clients
4. somehow it created a different connection though:
{"chain_id":"archway-1","channel_id":"channel-39","client_id":"07-tendermint-24","connection_hops":["connection-44"],"counterparty":{"chain_id":"secret-4","channel_id":"channel-90","client_id":"07-tendermint-169","connection_id":"connection-129","port_id":"wasm.secret1tqmms5awftpuhalcv5h5mg76fa0tkdz4jv9ex4"},"ordering":"ORDER_UNORDERED","port_id":"transfer","state":"STATE_OPEN","version":"ics20-1"}

That seems like unexpected behaviour - happy to better understand what to do next time or see this altered in the code.

**Comment by agouin** [comment]
You should use `rly tx channel` to create a new channel on an existing connection pair

**Comment by ertemann** [comment]
Really that simple?

So for connect the expected behaviour is to create a new connection?

**Comment by agouin** [comment]
Yes, `rly tx connection` creates a new connection on top of the configured clients for the path

**Comment by agouin** [comment]
Ah I see you used `rly tx connect`, which is an alias for `rly tx link`. That will create new connections unless existing connections are populated in the config for the path.

**Comment by ertemann** [comment]
thanks for the info!
