### ISSUE TITLE
Transition cli cmds to use x/ibc cli implementations

### ISSUE THREAD

**Issue by colin-axner** [cosmos/relayer#135]
Currently it seems all the cli commands are fully implemented on this repo and do not rely on the cli implementation on `x/ibc`. I think it would be useful to eventually transition these cli commands to use the `x/ibc` code since folks developing ibc will probably use that. If I'm not mistaken Game of Stakes provided good user feedback on cli interactions and bugs and Game of Zones will likely lead to the same feedback and usage

**Comment by jackzampolin** [comment]
@colin-axner I would accept a PR for that change. Please feel free!

**Comment by jackzampolin** [comment]
I've refactored the relayer and we now utilize `CLIContext` and other SDK code that was previously in relayer only. Closing as not actionable.
