### ISSUE TITLE
Question: rly tx link with custom client trusting periods for each client

### ISSUE THREAD

**Issue by ashishchandr70** [cosmos/relayer#1357]
Hi,

When creating the client/connection/channel in one go, I use `rly tx link ...`. Now, this command does support the `--client-tp` flag so I use it like so:

`rly tx link sagaxl --client-tp 403200s --override --src-port transfer --dst-port transfer --order unordered --version ics20-1`

This does create the client and the connection and channel but the `trusting_period` for both clients is set to the same value, which is not often the case as different chains can require different `trusting_period` values based on their chain's `unbonding_period`

This is one of the client's config after the above command completes successfully:

```
# rly q client axelar 07-tendermint-768 --log-format json|jq .
{
  "client_state": {
    "@type": "/ibc.lightclients.tendermint.v1.ClientState",
    "chain_id": "ssc-testnet-1",
    "trust_level": {
      "numerator": "1",
      "denominator": "3"
    },
    "trusting_period": "403200s",
    "unbonding_period": "1814400s",
    "max_clock_drift": "600s",
    "frozen_height": {
      "revision_number": "0",
      "revision_height": "0"
    }
...<snipped>...
```

Most chains require that you set the `trusting_period` to 2/3 of the `unbonding_period`.

Am I using the command incorrectly or should there be an option to set this for `chain_1` and `chain_2` separately in the `rly tx link` command?

I know I can do this separately by `rly tx client` for each chain separately but if we have `rly tx link`, it should not be too much work to introduce a flag for both chains separately.

Thank you

**Comment by boojamya** [comment]
Hi @ashishchandr70,

If you don't use the `--client-tp` flag, the relayer will create the trusting period based of each client separately (85% of the unbonding time).

So sounds like this is the answer you're looking for... just don't use that flag.

If you do use the flag, `rly tx link` will create the same specified trusting period for each client.

If you want separate custom trusting periods per client, you're correct, you'll need to run `rly tx client` separately for each chain.

**Comment by ashishchandr70** [comment]
Thanks @boojamya. The issue with the 85% of unbonding time is that most of the chains we are integrating with (Axelar, Osmosis) require the `trusting_period` to be 2/3 of Unbonding Period, and this `unbonding_period` is also not the same (at least in our testnet, our chain has an unbonding period of 21d whereas Axelar has a much lower number). This is of course just using `rly tx link` without the `--client-tp` flag.

I was hoping that this request can be considered for a future PR i.e. adding a separate `--client-tp` flag for each chain. For now, I can use `rly tx client` but then I lose the brevity of a `rly tx link`. If this is not something worthwhile, I will close this issue.

**Comment by boojamya** [comment]
Agree, this would be a great addition. 
Also easy to implement.

**Comment by boojamya** [comment]
Closed via: https://github.com/cosmos/relayer/pull/1365
