### ISSUE TITLE
v2.4.x - Update Client and ACKs in loop

### ISSUE THREAD

**Issue by RaulBernal** [cosmos/relayer#1359]
I want to discuss a recent issue we've discovered at BitCanna MainNet with some Go RLY (v2.4.x)
We have (at least) 3 relayers' providers that use Go Rly (v2.4.0 and v2.4.2) 

Relayed By ...... | rly(2.4.2)
Relayer by ...... | rly(2.4.0)
Relayed by ...... | rly(2.4.2)

They are the most "active" here: 
https://relayers.smartstake.io/network/BCNA

And we can observe that IBC client update & IBC ACKs are sent in loop every 30 seconds (and 15 seconds) for send_TXs that maybe were sent 17h ago (even 24h ago)
![image](https://github.com/cosmos/relayer/assets/3751926/ec8537ce-f671-42b4-843e-b959ec2ae643)
![image](https://github.com/cosmos/relayer/assets/3751926/407589e8-7c3b-4fb7-b7e6-2ed99523beaf)

Logs are "normal" we see a loop of UPDATE client and ACK 
https://cdn.discordapp.com/attachments/1153647572754378832/1182269540407713912/image.png?ex=6584154f&is=6571a04f&hm=3903148ba5319ec9a76be9b9ab5a68076a484e2b7d2c6e630198c228866d6136&

This behavior stops when they restart the rly daemon, but starts later again.

**Comment by RaulBernal** [comment]
Another sample (different relayer provider)
<img width="1435" alt="image" src="https://github.com/cosmos/relayer/assets/3751926/052547dd-b1a8-411f-99e0-664280f811c5">

**Comment by meetrick** [comment]
@RaulBernal Why do you think `IBC Acknowledgment` is a problem? 
It appears that your relayer account only processed the `IBC Acknowledge` packet.  
As for the client update happening periodically, can you share your relayer start command?
- https://www.mintscan.io/bitcanna/address/bcna1769cucyky8xhmhqv9aue5zlfhadasqhd49xpnx

**Comment by RaulBernal** [comment]
First things first :D Those are not my relayers, those relayers operate in my chain (BitCanna) and those 3 have a weird behavior. 

> @RaulBernal Why do you think `IBC Acknowledgment` is a problem? 
OFC is not a problem, but to send the same IBC ACK in loop for 17 hours every 15 or 30sec seems like a bug. Look the first two images. 


> It appears that your relayer account only processed the `IBC Acknowledge` packet. 
It's the normal start and a normal config (not customized) (this is that relayer's operators told me) 

When they reset it starts to work normally, relaying everything again, but this is a new report of a relayer provider:
![image](https://github.com/cosmos/relayer/assets/3751926/84a36b4e-2759-490b-95e0-1b6ebc661e5e)
You can see again the IBC ACK in loop 


> As for the client update happening periodically, can you share your relayer start command? 
It's not normal to update the client every 30 seconds / 15sec.

> * https://www.mintscan.io/bitcanna/address/bcna1769cucyky8xhmhqv9aue5zlfhadasqhd49xpnx
