### ISSUE TITLE
RLY should model gas fees for Block SDK enabled chains using the on-chain endpoint

### ISSUE THREAD

**Issue by ertemann** [cosmos/relayer#1368]
For Osmosis having a hardcoded fee is no longer sufficient since the implementation of erip1559.

Maybe RLY can enable setting the gas fee based on: https://lcd.osmosis.zone/osmosis/txfees/v1beta1/cur_eip_base_fee for enabled chains.

**Comment by ertemann** [comment]
Now supported in Hermes as such: https://github.com/informalsystems/hermes/pull/3771

**Comment by jtieri** [comment]
this is definitely high on our priority list! based on recent discussions it sounds like this may be prioritized during our next sprint.

**Comment by ertemann** [comment]
NICE
