### ISSUE TITLE
Help Needed: Error sending messages (Account Sequence Mismatch)

### ISSUE THREAD

**Issue by napelvs** [cosmos/relayer#1401]
I'm having the following error:

`2024-02-19T19:34:27.078100Z        error        Error sending messages        {"path_name": "celestia-umee", "src_chain_id": "umee-1", "dst_chain_id": "celestia", "src_client_id": "07-tendermint-245", "dst_client_id": "07-tendermint-58", "error": "rpc error: code = Unknown desc = rpc error: code = Unknown desc = account sequence mismatch, expected 47, got 48: incorrect account sequence [celestiaorg/cosmos-sdk@v1.18.3-sdk-v0.46.14/x/auth/ante/sigverify.go:269] With gas wanted: '18446744073709551615' and gas used: '296519' : unknown request"}`

I'm struggling to find what's the fix to this, as it occurs VERY often. I've tried the "trial and error" method but I haven't found a solution yet. Any help is MASSIVELY appreciated as it's driving me mad.

Also, what's the ideal way of getting some assistance with relayer-related issues?

Thank you in advance 🙏

**Comment by agouin** [comment]
There are two main ways this can occur:

- Using a wallet for more than one relayer instance simultaneously
- Pointing to an RPC with a load balancer instead of a single node

Do either of these apply to your setup?

**Comment by jtieri** [comment]
Closing as stale.
