### ISSUE TITLE
Ensure `msgUpdateClient` is not nil before appending to batch in `sendBatchMessages`

### ISSUE THREAD

**Issue by LeTrongDat** [cosmos/relayer#1406]
In the function [`sendBatchMessages`](https://github.com/cosmos/relayer/blob/11b7de318b5527b0f097475df1865fe472f76ff1/relayer/processor/message_processor.go#L423), there is a logic to prepend `mp.msgUpdateClient` to the beginning of the batch. However, in cases where `needsClientUpdate` is false, `msgUpdateClient` will be `nil`. This can lead to appending a nil value into the batch, which is likely unintended and could cause issues downstream. It's necessary to introduce a check to ensure `msgUpdateClient` is not nil before appending it to the batch. This precaution would prevent potential errors or unexpected behavior during the message processing workflow.

**Comment by jtieri** [comment]
Hey @LeTrongDat I think this was also fixed in #1407, does that seem correct?

**Comment by jtieri** [comment]
> Hey @LeTrongDat I think this was also fixed in #1407, does that seem correct?

I believe this was closed out in the issue that i mentioned here. Feel free to re-open this issue if necessary but for now i'm going to close this out.
