### ISSUE TITLE
Add support query ibc-denoms for a given chain id and path

### ISSUE THREAD

**Issue by tnv1** [cosmos/relayer#1416]
Context: 

I'm working with fee-abstraction and I need a cli to query ibc token denom when relayer is created between 2 chains.

Need support add query looks like:

`rly q ibc-denoms <chain_name> <path>`

Example:
`rly q ibc-denoms osmosis transfer/channel-6072`

should be returns:

`62DDD1848B6F9182A658B6E88D7625F71D863E678ED043660692BD307C9217A0`

**Comment by jtieri** [comment]
Thanks for opening an issue. This seems like a useful command to have and should be easy enough to add, perhaps it can be included in a future release.

**Comment by jtieri** [comment]
I actually just opened a PR to add this new query now. Feel free to checkout and use that branch or the main branch once it is merged until it is included in our next release. 

Hope this helps!

**Comment by tnv1** [comment]
Awesome! Thanks very much @jtieri
