### ISSUE TITLE
node configuration

### ISSUE THREAD

**Issue by TaurusCar** [cosmos/relayer#1417]
There are some problems with the faucet and any problem with configuration nodes syc problem

**Comment by jtieri** [comment]
Hey, thanks for opening an issue. Can you confirm what you mean in your original post? The relayer does not offer a faucet so I am a bit confused by your issue.

**Comment by reecepbcups** [comment]
Closing as stale - faucets are handled upstream on a per network basis & not related to relayer operations.

Please reach out to network teams who run said mainnet/testnet faucets to get coins
