### ISSUE TITLE
GenesisL1 chain problems

### ISSUE THREAD

**Issue by StakeandRelax-Validator** [cosmos/relayer#1420]
Hello, I'm trying to configure GenesisL1 relayer to Osmosis but I'm getting some problems.
Default coint type in chain registry is 118, but on chain is 60 (so maybe chain registry is wrong).
Also default algo is ethsecp256k1

So my tow test had been:
- create a key with coin-type null (default from chain registry so 118) and in this case rly works sending packets but fails with ack (from genesis to osmosis)
{"src_chain_id": "osmosis-1", "dst_chain_id": "genesis_29-2", "src_client_id": "07-tendermint-1983", "dst_client_id": "07-tendermint-1", "msg": {"type": "acknowledge_packet", "src_port": "transfer", "src_channel": "channel-1", "dst_port": "transfer", "dst_channel": "channel-253", "sequence": 7901, "timeout_height": "1-14252543", "timeout_timestamp": 0, "data": "eyJhbW91bnQiOiIxMDAwMDAwMDAwMDAwMDAwMDAwIiwiZGVub20iOiJlbDEiLCJyZWNlaXZlciI6Im9zbW8xY2QwMDQ3N2tjOHl4bnk3N3JzN2pwc3B3OHV2Y3pjbG1hcXAzdnIiLCJzZW5kZXIiOiJnZW5lc2lzMWNkMDA0NzdrYzh5eG55NzdyczdqcHNwdzh1dmN6Y2xtdGp4aDd5In0=", "ack": "eyJyZXN1bHQiOiJBUT09In0="}, "error": "no concrete type registered for type URL /ethermint.types.v1.EthAccount against interface *types.AccountI"}

- modify the configuration with coin-type 60 and importing a key created on genesisd bynary (address matched). On starting rly I get
Error: key coin60test not found on chain genesis_29-2
obviously coin60test was written in the configuration of GenesisL1 chain

Actyally there seems to be also a problem with the tx from Osmosis to GenesisL1, that continuos to fail directly before even going on chain (from both Keplr and Osmosis)..

**Comment by jtieri** [comment]
> Hello, I'm trying to configure GenesisL1 relayer to Osmosis but I'm getting some problems. Default coint type in chain registry is 118, but on chain is 60 (so maybe chain registry is wrong). Also default algo is ethsecp256k1
> 
> So my tow test had been:
> 
> * create a key with coin-type null (default from chain registry so 118) and in this case rly works sending packets but fails with ack (from genesis to osmosis)
>   {"src_chain_id": "osmosis-1", "dst_chain_id": "genesis_29-2", "src_client_id": "07-tendermint-1983", "dst_client_id": "07-tendermint-1", "msg": {"type": "acknowledge_packet", "src_port": "transfer", "src_channel": "channel-1", "dst_port": "transfer", "dst_channel": "channel-253", "sequence": 7901, "timeout_height": "1-14252543", "timeout_timestamp": 0, "data": "eyJhbW91bnQiOiIxMDAwMDAwMDAwMDAwMDAwMDAwIiwiZGVub20iOiJlbDEiLCJyZWNlaXZlciI6Im9zbW8xY2QwMDQ3N2tjOHl4bnk3N3JzN2pwc3B3OHV2Y3pjbG1hcXAzdnIiLCJzZW5kZXIiOiJnZW5lc2lzMWNkMDA0NzdrYzh5eG55NzdyczdqcHNwdzh1dmN6Y2xtdGp4aDd5In0=", "ack": "eyJyZXN1bHQiOiJBUT09In0="}, "error": "no concrete type registered for type URL /ethermint.types.v1.EthAccount against interface *types.AccountI"}
> * modify the configuration with coin-type 60 and importing a key created on genesisd bynary (address matched). On starting rly I get
>   Error: key coin60test not found on chain genesis_29-2
>   obviously coin60test was written in the configuration of GenesisL1 chain
> 
> Actyally there seems to be also a problem with the tx from Osmosis to GenesisL1, that continuos to fail directly before even going on chain (from both Keplr and Osmosis)..

the first issue you described seems related to the codec type used for the accounts, seeing they are using ethermint i would have suspected this to work without issue though since [we do have codecs in place for ethermint](https://github.com/cosmos/relayer/tree/main/relayer/codecs)

if they are an EVM based chain i would think they are using coin type 60 so that would make more sense to me.

the second issue looks like the account just does not exist, simply deriving keys is not enough it needs to have funds for it to be created on chain iirc.

**Comment by jtieri** [comment]
Haven't heard a response on this in some time, i'm going to close the issue out feel free to re-open if necessary.
