### ISSUE TITLE
Tx Link issues

### ISSUE THREAD

**Issue by jackzampolin** [cosmos/relayer#149]
In the case where client creation fails, connection creation is skipped, but channel creation is tried.

**Comment by jackzampolin** [comment]
```
query channel failed: ABCIQuery: Post failed: Post "http://testnet.dawns.world:26657": read tcp 10.128.0.6:46864->47.74.39.90:26657: read: connection reset by peer 
```

Retry the channel queries

**Comment by cwgoes** [comment]
Have you considered making this command interactive - e.g. prompting the user whenever a step of the handshake fails as to whether they want to continue or not? On mainnet these transactions will cost gas (= $$), so users might want more conservative default retry behaviour.

**Comment by jackzampolin** [comment]
@cwgoes I am extremely averse to making any of these commands interactive and in fact have explicitly avoided doing so. This leads to a lot more complexity and makes scripting with the relayer hard. I think that when users run a command it should reasonably retry to push through most errors for things like failed queries.

**Comment by cwgoes** [comment]
Fair enough!

**Comment by jackzampolin** [comment]
Closing this issue as we have added retries in a number of places.
