### ISSUE TITLE
List of paths / showing a path should show sequence numbers & channel type

### ISSUE THREAD

**Issue by cwgoes** [cosmos/relayer#162]
When paths are pretty-printed with `rly paths list` or `rly paths show`, it would be nice to see:

- Type of channel (ordered or unordered)
- Current send sequence & receive sequence on each side (maybe only with `show`) and some status indicator to mark whether or not unrelayed packets are in the queue

**Comment by jackzampolin** [comment]
I don't know about adding anything additional to `rly pth l` because we are already running into perf issues there 🙊 but adding all these features to show would be very helpful. Going to do this.
