### ISSUE TITLE
Add watch command to pretty-print IBC-relevant logs

### ISSUE THREAD

**Issue by cwgoes** [cosmos/relayer#164]
I think it might be useful to have a sort of `relayer watch` command, which:

- Watches event logs on all configured chains (for which light clients have been set up)
- Pretty-prints all events related to IBC: client creation, client updates, handshake steps, packets, acks, timeouts, etc.
- Displays helpful metadata (e.g. which relayer relayed the packet, time delay between send/receive)

The command could accept arguments to filter the logs.

The relayer is well-suited to do this since these logs would be most useful when viewed from multiple chains at once (e.g. to debug whether packets are being received or not & when), and the relayer is already designed to connect to multiple chains.

I guess this is a bit similar to `rly development listen`? I think this would be useful in production, though, not just development, and most useful with multiple chains at once.

**Comment by jackzampolin** [comment]
I think that making this output data in a metrics format for ingest by something like prometheus, influx or datadog would be really really cool and something I plan to build into the relayer.

**Comment by jackzampolin** [comment]
This is currently implemented in `rly dev listen`, additional improvements to this code will be implemented there.

**Comment by AdityaSripal** [comment]
The command we have now is `rly dev listen` looks like a good start! Could we get it to print from all chains as a starting default along with the metadata information @cwgoes mentioned above? 

> Displays helpful metadata (e.g. which relayer relayed the packet, time delay between send/receive)

I think when used as a default, this would most likely be piped into some other metric processing framework. However, to be usable barebones it would be also nice to have certain filters on the logs passed in as optional flags in the cli:

1. Filter on chain-id
2. Filter on sending relayer
3. Filter on a specific event field

May be too complicated to implement this for now, but what could also be useful for debugging is filtering on minimum time delay between send/receive
