### ISSUE TITLE
Relay command should print out transactions sent

### ISSUE THREAD

**Issue by cwgoes** [cosmos/relayer#165]
It seems `rly transact relay [path]` does not pretty-print transactions by default - can it do that (just like `rly start [path]` does, maybe with a flag? It is very helpful.

**Comment by jackzampolin** [comment]
This is the output given when running it which is the same as the `rly start` output:
```
$ rly tx rly pyloncapychain 
I[2020-04-27|22:01:42.631] ✔ [capychain]@{7409} - msg(0:update_client,1:ics04/opaque,2:ics04/opaque) hash(5A4C3F36674C84CF6F413CD1C586062E5759C9FE54FAB14AC97AE4228EFDFDDF) 
I[2020-04-27|22:01:42.631] ★ Relayed 2 packets: [pylonchain]port{transfer}->[capychain]port{transfer} 
```
Is this sufficent?

**Comment by cwgoes** [comment]
Hmm, maybe I just did it incorrectly for some reason. If that is the output, that looks fine. Closing.
