### ISSUE TITLE
A tx is a combination of two txs. Data inconsisency on chain.

### ISSUE THREAD

**Issue by harsh-98** [cosmos/relayer#188]
Other weird issue that , I found is below packet has two txs and the second tx in array has two is itself a combination of two tx

- one( from pylon to my chain in pylon )
- second ( from pyloon to everstake in evertake ).

How can be a tx combination of 2 txs? Because of this, i can not relay all the packets in my channel from pylonchain to setanchain(my chain). While relay the packets i got error at this line. https://github.com/iqlusioninc/relayer/blob/master/relayer/naive-strategy.go#L242

For getting that packet.

> rly q txs pylonchain 
```
"send_packet.packet_src_channel=heyjusbiqh&send_packet.packet_sequence=11"
```

I am also pasting that packet. Checkout the second tx:
https://gist.github.com/harsh-98/9c9f75f34fb617e8f953820383886637#file-packet-json-L149.

**Comment by jackzampolin** [comment]
This is a very odd issue. Will look into it in detail soon.

**Comment by jackzampolin** [comment]
Closing as the code has changed substantially. I also believe that this issue is fixed.
