### ISSUE TITLE
Bug： Amino:JSON int/int64/uint/uint64 expects quoted values for javascript numeric support, got: 80.) 

### ISSUE THREAD

**Issue by liangping** [cosmos/relayer#212]
$rly tx link ping2kava
E[2020-05-01|01:22:05.315] - [kava-ibc] -> err(invalid character -- Amino:JSON int/int64/uint/uint64 expects quoted values for javascript numeric support, got: 80.)

**Comment by jackzampolin** [comment]
I've been unable to consistently reproduce this issue and I'm pretty sure it has to do with version mismatch. If you continue to see this error please reopen the issue
