### ISSUE TITLE
rly chains add  = Error: time: invalid duration, but→ rly chains add-dir $PATH= oke 

### ISSUE THREAD

**Issue by iammelea** [cosmos/relayer#216]
when ```"trusting-period":"90m"```
```
rly chains add -f melea-111.json = no works
Error: time: invalid duration 
```
but same 90m time

```
rly chains add-dir $PATH = works fine
```

**Comment by jackzampolin** [comment]
this is a chains add issue. know how to fix. will push v0.3.2 with this soon

**Comment by jackzampolin** [comment]
Not running into this issue with the current version. Please reopen if you continue to see this.
