### ISSUE TITLE
Cannot use tokens from expired clients

### ISSUE THREAD

**Issue by anilcse** [cosmos/relayer#229]
I got to see something strange today. I am not sure if this is a bug. Looks strange.

Scenario:
I have created a connection between `aneka` and `gameofzoneshub-1a` chians and did a few token transfers.
Later the connection got expired and I had to create a new client/connection ...

When I try to transfer tokens, it says, balance is zero. I am sure I have balance but the path is different.
![1a](https://user-images.githubusercontent.com/3479820/81345067-73980d80-90d5-11ea-94bd-19b625444892.png)

After that, I transfered some tokens from source chain.

![2a](https://user-images.githubusercontent.com/3479820/81345110-814d9300-90d5-11ea-930e-81dfc6744c51.png)

Now I am able to transfer back the tokens
![3a](https://user-images.githubusercontent.com/3479820/81345141-8ad6fb00-90d5-11ea-90ea-9c4e5d92b671.png)

Is this an expected behaviour?

/cc @jackzampolin

**Comment by jackzampolin** [comment]
cc @cwgoes @AdityaSripal @ancazamfir

**Comment by cwgoes** [comment]
A new channel will have a different token denomination; this is expected behaviour.

**Comment by anilcse** [comment]
I havent checked this in time. Would be curious to understand, what happens to the tokens which stayed in an expired channel? 
@cwgoes

**Comment by cwgoes** [comment]
They are inaccessible, the channel will need to be manually recovered by governance (once supported).

**Comment by anilcse** [comment]
Can I report this as a bug/missing feature or is it being tracked somewhere?

**Comment by dtribble** [comment]
Shouldn't timeout of the packets in the dead channel result in return of the tokens in timed-out packets?

**Comment by anilcse** [comment]
> Shouldn't timeout of the packets in the dead channel result in return of the tokens in timed-out packets?

I think that is not possible as the channel is closed.

**Comment by dtribble** [comment]
A closed channel should be specified to timeout all unacknowledged packets. That way there is a single pathway for recovery (esp. recovery of assets embedded in packets).

> 1.2.12 Deliver-or-timeout safety
> Deliver-or-timeout safety is the property that a packet will either be delivered & executed or will timeout in a way that can be proved back to the sender.

BUT in 5.2.3 of spec rc5:

> 3 If a client can no longer be updated (if, for example, the trusting period has passed), it will no longer be possible to send any packets over connections & channels associated with that client, or timeout any packets in-flight (since the height & timestamp on the destination chain can no longer be verified). Manual intervention must take place to reset the client state or migrate the connections & channels to another client. This cannot safely be done completely automatically, but chains implementing IBC could elect to allow governance mechanisms to perform these actions (perhaps even per-client/connection/channel in a multi-sig or contract).

So we will discuss whether we can do the fully-automated thing.

**Comment by anilcse** [comment]
Hmm, I see a lot of UX issues with gov process around this. May be a contract would improve it a bit
