### ISSUE TITLE
go releaser

### ISSUE THREAD

**Issue by tac0turtle** [cosmos/relayer#247]
what builds are wanted for releases. 

Would a docker hub deployment be needed?
Brew install?

This is currently how i have it setup. https://github.com/marbar3778/relayer/releases/tag/v0.0.2

**Comment by jackzampolin** [comment]
Docker and brew would be optional but nice to have. Like that a lot. I think this is going to require me to have a changelog strategy right?

**Comment by jackzampolin** [comment]
Still need to do this. Akash does something slightly different than goreleaser, but need some automation here to help me out.

**Comment by jackzampolin** [comment]
we haz it now!
