### ISSUE TITLE
Generate chain specific keys (address-prefixes)

### ISSUE THREAD

**Issue by anilcse** [cosmos/relayer#25]
`rly keys add $CHAINID $RLYKEY` is generating `cosmos` prefix-accounts. It should be chain specific

**Comment by jackzampolin** [comment]
Thanks for opening this @anilCSE!

**Comment by kwunyeung** [comment]
It should also get the correct `coinType` so that the address will match the wallet generation on the chain. If it's not pulled from the channel, how about adding optional flags for custom prefix and hd-path?

The PR #38 is using `desmos` as prefix and the coinType is `852`.

**Comment by anilcse** [comment]
Looks like this is popped up again. @jackzampolin is the support for different prefixes removed?
