### ISSUE TITLE
Panic on goz-dump

### ISSUE THREAD

**Issue by cyborgshead** [cosmos/relayer#252]
Tried to get hub connection with rly (v0.5.2)
```rly development goz-dump gameofzoneshub-1b```
and took panic
```panic: interface conversion: exported.ClientState is types.ClientState, not types.ClientState (types from different packages)```

**Comment by jackzampolin** [comment]
@litvintech This is because the `rly dev goz-dump` command is only compatible with `gameofzoneshub-1a` and not yet `-1b`. See PR https://github.com/iqlusioninc/relayer/pull/237

**Comment by jackzampolin** [comment]
I think this is closed by #257
