### ISSUE TITLE
scripts assume archaic GOPATH is set

### ISSUE THREAD

**Issue by tac0turtle** [cosmos/relayer#282]
Scripts assume `GOPATH` is set. It would be nice to have it not assume this as it is not standard any longer.

Also, the link (https://golang.org/doc/install) to download go does not provide instructions for setting GOPATH anymore. 

scripts should just clone gaia into the repo and then remove it before shutting down

**Comment by jackzampolin** [comment]
You are calling my beloved `GOPATH` archaic!! How dare you! 

But for real, cloning them into a `.gitignore`d folder that has something like `make chain-code-fetch` and `make chain-code-delete` to dl them would be good change.

**Comment by jackzampolin** [comment]
Ok I've gone ahead and fixed this issue with the solution described and done a minor refactor of the scripts to make them more extensible.

**Comment by tac0turtle** [comment]
> You are calling my beloved `GOPATH` archaic!! How dare you!

 oops ❤️
