### ISSUE TITLE
Cannot start two-chainz on a Ubuntu machine

### ISSUE THREAD

**Issue by andynog** [cosmos/relayer#283]
I get several errors when running the script. Looks like some related to commands that cannot run on Linux (e.g. sed) the way outlined. Also looks like some errors due to nonexistent folders and some race conditions on gaiad commands.

I'm using the **stargate-3** tag for the relayer.

**Environment**:
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal

**Comment by jackzampolin** [comment]
@andynog thanks for the improvements and changes to the scripts! I'm going to close this as your PR addresses the issue you were facing.
