### ISSUE TITLE
when executing bin/rly testnets request ...,   error : gasUsed: 1000: out of gas\n #65

### ISSUE THREAD

**Issue by jonathan2004** [cosmos/relayer#286]
/> bin/rly testnets request chain_1 faucet -u http://127.0.0.1:8000 --home data/relayer
{"error":"transaction failed to execute\nResponse:\n TxHash: DD779702E8CC32B8547C13C7CC229D2A7E254D24E348F4A4CFAE244D9596512D\n Code: 11\n Raw Log: out of gas in location: ReadFlat; gasWanted: 0, gasUsed: 1000: out of gas\n GasUsed: 1000\n Codespace: sdk"}

why and how to resolve above question?

/> bin/gaiad version --long
name: gaia
server_name: gaiad
version: stargate-3
commit: 5f28583b510a86fac671e4590d0863d56989735d
build_tags: netgo,ledger
go: go version go1.15.2 linux/amd64

/>bin/rly version
version: ""
commit: ""
cosmos-sdk: v0.34.4-0.20200921130040-27db2cf89772
go: go1.15.2 linux/amd64

get relayer from https://github.com/ovrclk/relayer/releases/tag/stargate-3

**Comment by jackzampolin** [comment]
Have fixed this issue in upstream. Need to increase the gas adjustment in the chain config if you continue to run into the issue.
