### ISSUE TITLE
add flag to rly keys list to show all keys

### ISSUE THREAD

**Issue by colin-axner** [cosmos/relayer#294]
Currently `rly keys list` requires a chainID as an argument. It'd be nice to be able to list out all the keys added. My preference would be to always list all the keys by default and have `--chain-id` be a optional flag to filter by chain-id (possibly more than 1?)

**Comment by jackzampolin** [comment]
@colin-axner I don't necessarily agree this is desirable. The keys are stored on disk on a per chain basis and this is pretty baked in. I think keeping it the way it is is preferable.

**Comment by colin-axner** [comment]
Sounds reasonable to me
