### ISSUE TITLE
Keyring needs to support non-test keys to be used in production

### ISSUE THREAD

**Issue by colin-axner** [cosmos/relayer#298]
Currently the Keybase is created using a [test backend](https://github.com/ovrclk/relayer/blob/06740742e8e88baaff21efa5633c81a170d5ea24/relayer/chain.go#L138) this means no password is used to retrieve and use the keys. This is very useful for testing but this relayer is expected to be used in production. Therefore it needs to support other backend options like [OS](https://github.com/cosmos/cosmos-sdk/blob/c0122ad1b85555a305e681f8cd5fb86691136b4e/crypto/keyring/keyring.go#L32)

**Comment by jackzampolin** [comment]
@colin-axner the problem with that is there is no other non-interactive way to support signing. If users would like to this in production we suggest they keep limited funds in the relayer and keep the process in a secure environment.
