### ISSUE TITLE
Relayer should return an error if a channel already exists but belongs to a different connection

### ISSUE THREAD

**Issue by colin-axner** [cosmos/relayer#312]
I created several connections with the same channel in the config. After the first connection was created, calling `rly tx link` on the others would result in the channel handshake steps being skipped, this is because the channel already exists, but it just has a different connection than the ones being created

**Comment by jackzampolin** [comment]
@colin-axner how would you check for this?

**Comment by colin-axner** [comment]
Before executing, create connection and create channel, the channel should be queried using the gRPC routes. If it exists the connectionHops[0] needs to equal the connection that would have been created

**Comment by colin-axner** [comment]
this is encompassed in #345
