### ISSUE TITLE
Dynamic unbonding time

### ISSUE THREAD

**Issue by zmanian** [cosmos/relayer#32]
Currently unbonding time is hardcoded in the client creation command. We should have this be populated via the chain configuration.

Original issue:https://github.com/cosmos/relayer/issues/56

**Comment by cwgoes** [comment]
Yes, and additionally, when creating *IBC* light clients, it should be possible for the user to specify the unbonding period & trusting period (which is a parameter in client creation) in the configuration.

**Comment by jackzampolin** [comment]
This has been fixed by fetching the chain params for client creation. closing
