### ISSUE TITLE
How to Install IBC in external Blockchains (Ethereum, Hyperledger Fabric)

### ISSUE THREAD

**Issue by himankgupta31** [cosmos/relayer#328]
Dear Community,

I am currently doing hands-on with Relayer. I can able to transfer tokens across two cosmos based Blockchain (using Gaia) successfully.

I want to extend the above experiment further to the non-COSMOS based Blockchain, i.e. Ethereum, Hyperkedger-Fabric, IOTA, etc.
As a starting point, I want to transfer ethers across two Ethereum private chains.
Is it possible to realize above use-cases using Relayer code?

Any help or hint will be a great breakthrough for me.

**Comment by colin-axner** [comment]
Hello @himankgupta31 :wave: 

Any blockchain which wants to use IBC needs to be capable of speaking IBC. This would require Ethereum or whichever blockchain to present some way of accepting IBC transactions. I am not aware of any non-cosmos blockchain which currently supports this since the cosmos SDK's golang module should be the first implementation of IBC. Any cosmos blockchain which upgrades to the stargate version will be capable of supporting IBC if they include IBC in their application file. 

More info can be found in the [IBC docs](https://docs.cosmos.network/master/modules/ibc/#). You'll also get a more responsive answer on the cosmos discord about these sorts of questions.

**Comment by himankgupta31** [comment]
Hello Colin

Thanks for your reply.

I agreed with you that other BCs should understand IBC. 
I intend to have IBC as TCP/IP protocol which can be installed on any BC. SO far I can see IBC code as a relayer only, and through Gaia, COSMOS-based BC can communicate.

Ethereum is also on golang platform, so my idea is to start deploying IBC relayer code on two Ethereum private chain and establish a communication.
I also posted the same on COSMOS forum. I will post on discord as well.

**Comment by colin-axner** [comment]
The relayer is only capable of relaying IBC messages, specifically just IBC messages based on the golang cosmos IBC implementation. The actual golang IBC implementation is [here](https://github.com/cosmos/cosmos-sdk/tree/master/x/ibc). It is made to be modular such that parts can be reused but certain parts are cosmos and even Tendermint specific so it cannot be easily plugged into a new blockchain. 

Ethereum would likely require a smart contract to be written which is capable of executing core IBC logic. Alternatively a peg zone can be used to interact with etherum and then the peg zone will be capable of speaking IBC with other chains

**Comment by himankgupta31** [comment]
Hello

My objective is to reuse the IBC module in Ethereum Private chains. I am struggling to bypass the Tendermint logic from the original IBC.

I have explored the peg-zone-based solution (Peggy) but it creates many dependencies to establish communication with external Blockchain. So, I am more inclined towards an IBC based solution for external blcockchains.

**Comment by colin-axner** [comment]
Sorry that I'm being so indirect.

> My objective is to reuse the IBC module in Ethereum Private chains. I am struggling to bypass the Tendermint logic from the original IBC.

I don't think this is possible at the moment, without adding in a non-trivial amount of code (like a projects worth). The IBC module also makes the assumption the consensus algorithm is tendermint (unfortunately) so this requires basically a rewriting of several parts of core IBC in the context of ethereum code.

Using Ethermint would be your best option, but I don't think it supports IBC yet. It certainly would support IBC much earlier than on an Ethereum private chain

**Comment by colin-axner** [comment]
closing this issue since it is not dev related, but I'll still respond to further comments on here
