### ISSUE TITLE
relayer/cmd.filesAdd: seemingly missing continue or wrong message talking about skipping, yet falling through

### ISSUE THREAD

**Issue by odeke-em** [cosmos/relayer#331]
While reading through this code, I noticed this code https://github.com/cosmos/relayer/blob/031ecc2e304af39c789acd0f1b84033d3b8ef4d2/cmd/chains.go#L310-L318

The last line says https://github.com/cosmos/relayer/blob/031ecc2e304af39c789acd0f1b84033d3b8ef4d2/cmd/chains.go#L316
but then falls through and adds file to the chain. Was this intended?

Kindly cc-ing @jackzampolin

**Comment by jackzampolin** [comment]
Thanks for catching this @odeke-em, there are def some issues like this in the code. Thanks for the catch!
