### ISSUE TITLE
relayer/cmd.cfgFilesAdd: missing continue after encountering an error

### ISSUE THREAD

**Issue by odeke-em** [cosmos/relayer#332]
In this code https://github.com/cosmos/relayer/blob/031ecc2e304af39c789acd0f1b84033d3b8ef4d2/cmd/config.go#L192-L197 a JSON Unmarshal error occurred and the message even says skipping but it didn’t skip. We need to add a continue here. This code is similar to https://github.com/cosmos/relayer/issues/331

**Comment by colin-axner** [comment]
fixed in #344
