### ISSUE TITLE
Implement bottom up path validation

### ISSUE THREAD

**Issue by colin-axner** [cosmos/relayer#345]
The current code does little path validation since the required identifiers recently changed in #334 

This should be implemented as @AdityaSripal specifies in this [comment](https://github.com/cosmos/relayer/issues/329#issuecomment-733705336)

**Comment by colin-axner** [comment]
tagging for akash

This is very useful for helping spot invalid config files which would likely lead to very confusing errors from the relayer. This should also handle cases where the connection identifier defined doesn't have the specified parameters (the client ID doesn't match with that for the defined connection ID)

cc @gosuri @akhilkumarpilli @anilCSE @boz

**Comment by akhilkumarpilli** [comment]
> tagging for akash
> 
> This is very useful for helping spot invalid config files which would likely lead to very confusing errors from the relayer. This should also handle cases where the connection identifier defined doesn't have the specified parameters (the client ID doesn't match with that for the defined connection ID)
> 
> cc @gosuri @akhilkumarpilli @anilCSE @boz

We are looking on this.

**Comment by akhilkumarpilli** [comment]
@colin-axner, From where do we need to check existing connections or channels,  from config or querying from chain?

**Comment by colin-axner** [comment]
If the configuration sets a client/connection/channel, the code needs to ensure that the set identifiers makes sense and that they exist. 

If a configuration sets a channel identifier, but not a client identifier, this is wrong, as per bottom up validation. Channels must have an associated client so therefore the config should ensure that client identifier is set.

If a configuration sets a connection ID, but that connection does not exist on chain, we should return an error

These are specific examples, but that's the general idea
