### ISSUE TITLE
Add staking amount to gentx for scripts [stargate][v0.40.0]

### ISSUE THREAD

**Issue by alpe** [cosmos/relayer#353]
With gaiad (`d974b27`) the ` ./scripts/two-chainz` script fails (on my box) with:
`Error: post failed: Post "http://localhost:26657": dial tcp [::1]:26657: connect: connection refused`

In the server log:
```
Error: error during handshake: error on replay: validator set is nil in genesis and still empty after InitChain
```

The root cause is the new argument for gaiad gentx which was introduced recently. 
```sh
Usage:
  gaiad gentx [key_name] [amount] [flags]
```

It affects this script https://github.com/cosmos/relayer/blob/master/scripts/one-chain#L67 and doc

**Comment by colin-axner** [comment]
looks like it was fixed in #537
