### ISSUE TITLE
Automatic Updates to clients to prevent expiry

### ISSUE THREAD

**Issue by colin-axner** [cosmos/relayer#395]
The golang relayer needs to be able to maintain on-chain clients without manual intervention. IG will handle this issue since it is necessary for Stargate

**Comment by colin-axner** [comment]
@anilCSE @akhilkumarpilli if y'all would like to take this on, that would be good. Otherwise we will do it at some point. This definitely needs to be a tested feature though

**Comment by akhilkumarpilli** [comment]
Sure @colin-axner , we will look into this.
