### ISSUE TITLE
Failed to initialize light client when the number of validators is equal 100

### ISSUE THREAD

**Issue by chengwenxi** [cosmos/relayer#396]
**Summary**

`rly light init` return error when the number of validators is equal 100, may be caused by https://github.com/tendermint/tendermint/issues/6010.

**Comment by colin-axner** [comment]
Definitely caused by the tendermint issue. That command calls the tendermint light client API to initialize a light client. Thanks for opening an issue

**Comment by colin-axner** [comment]
should be fixed now that we are on v0.34.7 of TM
