### ISSUE TITLE
DOCUMENTATION: Demo the relayer

### ISSUE THREAD

**Issue by jackzampolin** [cosmos/relayer#404]
The current documentation for demoing the relayer is significatly out of date. However, it does seem that the `./two-chainz` script spins up 2 gaia instances and `./dev-env` almost works. Is there an example of running the relayer demo anywhere? Happy to update the README if I can find it.

**Comment by colin-axner** [comment]
On this note, I think the relayer desperately needs two pieces of documentation:
- the overall concepts/flow/ideas of what a relayer is doing, how it interacts chains, how wallets/exchanges would use it etc
- from a wallet/exchange point of view. What are the concrete steps needed to take to start relaying on a specific port/channel

**Comment by zramsay** [comment]
so the gif demo in the readme https://github.com/cosmos/relayer#demoing-the-relayer is out of date but the demo immediately following it still works. I ran through it a few days ago pretty much without issue and everything worked as described.

**Comment by colin-axner** [comment]
docs have been updated
