### ISSUE TITLE
Unbonding to Delegated

### ISSUE THREAD

**Issue by Oggysweep** [cosmos/relayer#405]
Hi, I have some unbonding AKT tokens on my phone and want to change them to Delegated, so I can have all in delegated.   How do I do this?
Also, I have a few AKT which are "available".  How do I move those to Delegated?
TIA

**Comment by colin-axner** [comment]
Hi, if AKT tokens belong to the cosmos ecosystem I suggest you checkout the cosmos [discord](https://discord.com/invite/AzefAFd). Relayer issues are reserved for relayer bugs and feature requests. Delegation is unrelated to IBC.
