### ISSUE TITLE
Remove Strategy Interface

### ISSUE THREAD

**Issue by colin-axner** [cosmos/relayer#407]
This relayer should be simplified and we can remove all the extra code glueing a strategy and the naive strategy. This will reduce UX complexity as well. Low priority

**Comment by fedekunze** [comment]
I think the minimal relayer should only implement the naive strategy (i.e user defines the route). Additional strategies could be added in the future as improvements

**Comment by colin-axner** [comment]
I'd prefer to leave additional strategies to more advanced relayers. This relayer should do one relayer strategy and it should do it well

**Comment by jackzampolin** [comment]
We need to remove the strategy interface.

**Comment by jtieri** [comment]
Strategy interface was removed in #535, maybe there is some cleanup needed still but should generally be good to go. Closing this for now
