### ISSUE TITLE
Client Creation should ensure pre-specified identifiers do not contain expired clients

### ISSUE THREAD

**Issue by colin-axner** [cosmos/relayer#417]
During client creation, if a clientID is set we should check it exists (done already) and that is isn't expired/frozen

**Comment by jtieri** [comment]
This is a good addition. 
we also want to ensure that the relayer checks if a client is frozen/expired before a Msg can be submitted

**Comment by jtieri** [comment]
We check if a client is frozen and/or expired in the call to `FindMatchingClient` during client creation. 
https://github.com/cosmos/relayer/blob/91a943d49e7c2cf4ca596bdab3101b31aa6a5de6/relayer/provider/cosmos/tx.go#L1533-L1582
Closing this issue.
