### ISSUE TITLE
Allow relayer to use non-tm clients 

### ISSUE THREAD

**Issue by colin-axner** [cosmos/relayer#420]
see [comment](https://github.com/cosmos/relayer/pull/416#discussion_r573701606). Using non-tendermint clients requires a large refactor and this should not be done anytime soon unless it reduces code complexity. This sort of feature requires a long term maintainer

**Comment by jtieri** [comment]
I believe we have all the pieces together now for this to take place via the `Provider` abstraction. Beefy light client integration into ibc-go is in the final steps and we should see integration tests for Cosmos<->Substrate IBC in the relayer or [IBC Test Framework](https://github.com/strangelove-ventures/ibc-test-framework) in the coming weeks.
