### ISSUE TITLE
Amount deducted from sender, but Relayer not relaying transaction

### ISSUE THREAD

**Issue by AbhinavMir** [cosmos/relayer#443]
I've been trying to send a transaction from chain A to chain B, but upon trying to transact using `Relay the tx using: rly tx rly PATHNAME -d`, the transaction is not going through. Everything else works fine, the chains are connected and from chain A, the amount is deducted. What am I doing wrong here?

**Comment by colin-axner** [comment]
Hello :wave: 

I'd suggest joining the cosmos [discord](https://discord.com/invite/AzefAFd) to get help. We will need more information on what is occurring to help you debug the issue. Is there any output from running `rly tx rly`?

**Comment by AbhinavMir** [comment]
Hi @colin-axner , I shared the question in the discord but got no response. `rly tx rly` is not giving any output. Should I add the steps I took for replication purposes? Thank you for your help.

**Comment by colin-axner** [comment]
Hi, did you try asking in #ibc-public or #ibc-relayer?

Try using the `-d` flag (debug)

**Comment by AbhinavMir** [comment]
`-d` gives no outputs either. I'm not able to join the #ibc-relayer or #ibc-public (messages not showing). Let me try that again.

**Comment by colin-axner** [comment]
> `-d` gives no outputs either. I'm not able to join the #ibc-relayer or #ibc-public (messages not showing). Let me try that again.

I think you need to visit the #show-channels channel

Providing the steps you took would help. I suspect something isn't setup properly
