### ISSUE TITLE
Upgrade chain needs to use IBC upgrade proposal

### ISSUE THREAD

**Issue by colin-axner** [cosmos/relayer#458]
Once the codebase is updated to ibc-go, [this](https://github.com/cosmos/relayer/blob/2a2dd3b0d8edb3bf2c23909a74b8968f82a5e6ff/relayer/chain.go#L715) needs to become an IBC upgrade proposal

**Comment by boojamya** [comment]
Not the relayers responsibility. Can re open if necessary.
