### ISSUE TITLE
query balance cmd returns duplicate responses

### ISSUE THREAD

**Issue by colin-axner** [cosmos/relayer#459]
```
rly tx transfer ibc-0 ibc-1 1000000samoleans $(rly chains address ibc-1)
rly tx transfer ibc-2 ibc-1 1000000samoleans $(rly chains address ibc-1)
rly tx rly demo -d
rly tx rly demo2 -d

rly q bal ibc-1

// result
1000000ibc/27A6394C3F9FF9C9DCF5DFFADF9BB5FE9A37C7E92B006199894CF1824DF9AC7C,
1000000ibc/27A6394C3F9FF9C9DCF5DFFADF9BB5FE9A37C7E92B006199894CF1824DF9AC7C,
1000000ibc/C1840BD16FCFA8F421DAA0DAAB08B9C323FC7685D0D7951DC37B3F9ECB08A199,
1000000ibc/C1840BD16FCFA8F421DAA0DAAB08B9C323FC7685D0D7951DC37B3F9ECB08A199,
100000000000samoleans,100000000000samoleans,100000000000stake,100000000000stake
```

**Comment by colin-axner** [comment]
This [code](https://github.com/cosmos/relayer/blob/2a2dd3b0d8edb3bf2c23909a74b8968f82a5e6ff/helpers/query.go#L40) is incorrect

We should be displaying the full denom trace and the `default` case should not add the coin to out. The code could be rewritten, we want to display the denom trace for each coin that is an IBC token. The ICS 20 query functions probably provide a better way of doing this

**Comment by colin-axner** [comment]
Tagging good first issue since it isn't hard to fix, but will take some time to fix if you are unfamiliar with IBC. Don't attempt to fix if you want something that takes less than 10 minutes

**Comment by colin-axner** [comment]
TODO: [Apply review comments](https://github.com/cosmos/relayer/pull/464#pullrequestreview-617515257)

**Comment by boojamya** [comment]
Closing.
