### ISSUE TITLE
proposal: remove commands.md

### ISSUE THREAD

**Issue by alexanderbez** [cosmos/relayer#469]
I propose we remove https://github.com/cosmos/relayer/blob/master/docs/commands.md.

I spent a bit of time cleaning up the CLI command UX only to realize I have to groom through this large doc and update it. I believe we should remove this doc for two primary reasons:

1. Continuous burden of maintenance and keeping the doc in sync with the actual CLI.
2. The CLI itself should and does act as its own source of documentation.
  2a. Anything that may cause confusion or that needs more explanation should be outlined and documented elsewhere, e.g. Readme, FAQ, Wiki, etc...

Would like to get an approval from @colin-axner, @jackzampolin  or @AdityaSripal

**Comment by colin-axner** [comment]
ACK - I completely agree. It is just extra maintenance debt
