### ISSUE TITLE
Correctly determine the next possible height to update to

### ISSUE THREAD

**Issue by colin-axner** [cosmos/relayer#476]
The relayer supports a mechanism to do automatic updates of the client if it is about to expire. This can potentially lead to the expiry of a client if we don't handle this properly. 

In order for a light client to be updated, the validator set that signed off on the block it is updating to, needs to match the trust level set on the client.

- A trust level of 1 means the blocks need to be verified sequentially (no changes in validator set).
- A trust level of 1/3 means at least 1/3 of the validator set needs to have signed off on the block being updated to. 

Validators are removed from the validator set as soon as they send an unbonding message. It is possible for the validator set to change completely within the unbonding period (or the trusting period) causing the automatic update to fail if the validator set changed too much and subsequently the client will probably become frozen

We should devise some way of gracefully handling this case. 
1) The relayer should use the connected light client to determine if the update it wants to do is valid before submitting it
2) It should do some sort of incremental updates (naively what comes to mind is splitting the time jump in half until we find a valid update)

cc @alexanderbez

**Comment by alexanderbez** [comment]
Great point @colin-axner! Are points (1) and (2) part of the same proposal or are they different approaches?

It seems to me that we need to find a way to balance performing frequent enough client updates within the trusting period but not too much as to have a high cost of running a relayer.

It also seems like no matter the approach we come up with, the problem might always exist because theoretically, a validator set could change by > 1/3 within a few blocks, where as making it seem like the only valid solution is to send updates on a blockly basis, which isn't practical or to rely/depend on epochs which not all chains might support.

**Comment by colin-axner** [comment]
(2) is dependent upon (1) but (1) can be done first. 

The relayer updates the IBC clients in two situations:
- relaying messages (updates client so client can verify proof)
- preventing expiry

Updates to past blocks are valid. So if we wait 1.5 weeks to update the client. We can first update to a block produced a 1 week ago and then .5 weeks ago and finally to the current block (if needed)

We will need to implement (2) for relaying packets to provide the most stability. We will need to pieces of functionality:
- determining the farthest block we can update to based on the latest client height
- updating from an old height to the latest height in a series of updates (will rely on the first feature)

Auto updating clients to prevent expiry relies on the first feature. If the client is about to expire, it wants to make 1 update to the latest block it can, then sleep until the time threshold for auto updating clients is surpassed again. 

Relaying messages will want to do a series of updates to update the client to the latest height so it can prove a packet sent or received in the latest height

**Comment by alexanderbez** [comment]
@colin-axner how do we determine which heights we need to update the clients for? Do you first go back as far as you can and incrementally check if the next height is valid to update?

**Comment by colin-axner** [comment]
@alexanderbez depends on the trade-offs we want to make. We could do guess work. Start from heights which cannot be updated to and guess what height might be a good candidate for verifying if it can be updated to. This is useful if we want to limit incrementally verifying every block. 

If we wanted to limit the number of update messages sent to the chain, then we would want to some how find the last block that allows a successful update. 

In tendermint, each update needs to be done from a root of trust. This root of trust is typically the latest block height of the IBC client. So you would try to determine the farthest block from the current block which allows for a successful update. We can discuss potential solutions in a live format, but there are a lot of options we could go with. 

We also want to keep in mind, these update strategies may be different for different types of cilents. It'd be great if we could keep this abstracted so other clients could plug in there own update strategy

**Comment by colin-axner** [comment]
I'm mostly opening these issues as context for items that should be accounted for when designing a relayer, since they need to be baked into the architecture

**Comment by boojamya** [comment]
Closing but referenced in newer issue above.
