### ISSUE TITLE
Relayer will return an error when trying to connect to secure websockets

### ISSUE THREAD

**Issue by PaddyMc** [cosmos/relayer#477]
### Description

The relayer will return a `bad handshake` error when trying to connect to secure websockets. This happens because the chain config specifies the `rpc-addr` as `https://`and the ws-client will default to unsecure websockets

This error stems from the ws-client in Tendermint-core:
- https://github.com/tendermint/tendermint/blob/master/rpc/jsonrpc/client/ws_client.go#L106-L109

To fix this issue we could change the logic in the ws-client from:

```go
        if parsedURL.Scheme != protoWSS {
		parsedURL.Scheme = protoWS
	}
```

to:

```go
	if parsedURL.Scheme == protoHTTPS {
		parsedURL.Scheme = protoWSS
	} else if parsedURL.Scheme != protoWSS {
		parsedURL.Scheme = protoWS
	}
```

but tbh I'm not sure if that's the best way to fix this issue, which is why I created an issue in this repo and not the tendermint core repo.

### Stack

1. https://github.com/cosmos/relayer/blob/master/relayer/chain.go#L143
2. https://github.com/cosmos/relayer/blob/master/relayer/strategies.go#L88

#### Set up

Use the configuration below to start a relayer

chain1
```json
{
  "key": "gaia",
  "chain-id": "cosmoshub-4",
  "rpc-addr": "https://rpc.cosmos.network:443",
  "account-prefix": "cosmos",
  "gas-adjustment": 1.5,
  "gas-prices": "0.025uatom",
  "trusting-period": "336h"
}
```
chain2
```json
{
  "key": "hackatom-gaia",
  "chain-id": "hackatom-ru",
  "rpc-addr": "https://gaia.hub.hackatom.org:443",
  "account-prefix": "cosmos",
  "gas-adjustment": 1.5,
  "gas-prices": "0.025uatom",
  "trusting-period": "336h"
}
```

paths
```json
{
  "src": {
    "chain-id": "cosmoshub-4",
    "client-id": "",
    "connection-id": "",
    "channel-id": "",
    "port-id": "transfer",
    "order": "unordered",
    "version": "ics20-1"
  },
  "dst": {
    "chain-id": "hackatom-ru",
    "client-id": "",
    "connection-id": "",
    "channel-id": "",
    "port-id": "transfer",
    "order": "unordered",
    "version": "ics20-1"
  },
  "strategy": {
    "type": "naive"
  }
}
```

#### Flow

```sh
rly config init

rly config add-chains ./chains
rly config add-paths ./paths

echo "cosmoshub seed:"
read ch
echo "hackatom seed:"
read ha

rly keys restore cosmoshub-4 gaia "$ch"

rly keys restore hackatom-ru hackatom-gaia "$ha"

rly light init cosmoshub-4 -f
rly light init hackatom-ru -f

rly tx link cosmoshub-transfer-hackatom -d

rly start cosmoshub-transfer-hackatom
```

### Notes

I'm happy to fix this issue but would love some input from @colin-axner, @alexanderbez  and @AdityaSripal on the correct way to fix this issue

Thanks :heart:

**Comment by alexanderbez** [comment]
Thanks for opening up an issue and clearing outlining the issue @PaddyMc!

You state:

>  but tbh I'm not sure if that's the best way to fix this issue, which is why I created an issue in this repo and not the tendermint core repo.

Can you expand upon why you think fixing the handshake logic in Tendermint Core is not the ideal or best approach? If there is a better solution, one that resides in the relayer itself, what would it be?

**Comment by PaddyMc** [comment]
Thanks for the quick response :bow: 

The [ws-client](https://github.com/tendermint/tendermint/blob/master/rpc/jsonrpc/client/ws_client.go) in Tendermint just says if the protocol is not `wss` it's `ws` so the assumption (although hacky) is correct when creating a websocket, we could add some fancy logic to the ws-client to say if the protocol is `https` we can assume that the websocket protocol is `wss` but I can for see this breaking some clients if the client has `https` but `ws` sockets. The fix in tendermint core would then turn into a series of `if this than that` checks that would essentially make the ws-client less flexible in the long run because we would need logic for every variation of the `http` and `ws` protocols

My suggestion would be to have a flag somewhere that tells the relayer that secure websockets are being used and when we are creating the websocket client:

- https://github.com/cosmos/relayer/blob/76eb658fb20a872b002ac4a523ac14f649132937/relayer/chain.go#L272

We pass in the correct URL with the correct protocol, in this case, `wss`,

 Or if that's not possible create a ws-client and attach it to the data structure returned by the `rpchttp.NewWithClient(addr, "/websocket", httpClient)` function call.

These are my initial thoughts on a solution would defo need to write some code to validate the assumptions I'm making tho. :thinking:

**Comment by alexanderbez** [comment]
Happy to review a PR @PaddyMc!

**Comment by colin-axner** [comment]
Short term solution in the golang relayer:
- parse addr into url, if url.Port() == "443", replace the scheme with wss

This fixes the issue at hand which is trying to create a ws with an endpoint that only supports secure connections

An issue can be opened on Tendermint to discuss the possibility of increasing the flexibility of deciding when a websocket is WSS. Even if Tendermint decides it doesn't want to change its current functionality, the documentation of the `NewWithClient` function should clearly state a WS connections will be attempted with a `https://myurl:443`, so that it is easier to be aware of this issue

**Comment by alexanderbez** [comment]
I haven't had success creating a websocket connection using a secure endpoint. I keep getting `dial wss: unknown network wss` or `bad handshake`.

**Comment by jackzampolin** [comment]
We have removed the websocket dependancy and no longer use any websockets. Closing this issue

**Comment by Red-Blink** [comment]
> Short term solution in the golang relayer:
> 
> * parse addr into url, if url.Port() == "443", replace the scheme with wss
> 
> This fixes the issue at hand which is trying to create a ws with an endpoint that only supports secure connections
> 
> An issue can be opened on Tendermint to discuss the possibility of increasing the flexibility of deciding when a websocket is WSS. Even if Tendermint decides it doesn't want to change its current functionality, the documentation of the `NewWithClient` function should clearly state a WS connections will be attempted with a `https://myurl:443`, so that it is easier to be aware of this issue

I am using version 1.0.0 and have issues related to what you said. I am using an https rpc, and whenever I want to connect the two chains, I get websocket: bad handshake. Is there anything that I can change to fix this error?
