### ISSUE TITLE
account sequence mismatch 

### ISSUE THREAD

**Issue by colin-axner** [cosmos/relayer#479]
```
rly tx raw  client musselnet-4 testnet-croeseid-2 test
Error: account sequence mismatch, expected 31, got 30: incorrect account sequence: invalid request
```

I don't see a way to fix this? Outside of maybe removing the key and restoring it

**Comment by AdityaSripal** [comment]
I'm having the same issue. Did removing and restoring work?

**Comment by anilcse** [comment]
We aer seeing a number of such errors on the osmosis relayer

**Comment by AdityaSripal** [comment]
I've seen the same issue on my own node trying to submit regular transactions. So i don't know if this is a relayer issue, or an issue on cosmos-sdk in general.

**Comment by jackzampolin** [comment]
This is more of an SDK issue because if you try to send multiple txs at the same time they each increment the sequence, easy for this to error. We take care of this with retires
