### ISSUE TITLE
Packet Commitment verification fails  on transfer with different account prefix

### ISSUE THREAD

**Issue by jhernandezb** [cosmos/relayer#48]
Packet commitment verification fails when transferring to a destination chain that uses a different prefix .

 I[2020-03-23|12:25:29.051] ✔ [ibc0]@{286} - msg(transfer) hash(CB9A024A586095C64540B3970026DA203BB0CD386305EE6D93DAE6786E7AB321) 
I[2020-03-23|12:25:30.307] - [ibc1] -> sending transaction:  
[TRANSACTION INFO](https://gist.github.com/jhernandezb/2e93e7d04d642f426189ebe25a5106eb)        

I[2020-03-23|12:25:30.308] ✘ [ibc1]@{0} - msg(ics20/transfer) err(client: packet commitment verification failed) 
```json
{
  "height": "0",
  "txhash": "E1D8903BB782104761074433A2CA0495FD00293CB525309E3039265B04A21E02",
  "codespace": "client",
  "code": 16,
  "raw_log": "packet commitment verification failed: verifying value: leaf value hash not same: invalid proof: couldn't verify counterparty packet commitment",
  "gas_wanted": "200000",
  "gas_used": "98142"
}
```

**Comment by cwgoes** [comment]
We should check how the destination address is being serialised, it may need to take the account prefix into account somehow.

**Comment by jackzampolin** [comment]
Should we move this issue over to Gaia?

**Comment by jackzampolin** [comment]
Closing this in favor of https://github.com/iqlusioninc/relayer/issues/43 as that was the first report.
