### ISSUE TITLE
Relayer needs to support disabled timeout heights

### ISSUE THREAD

**Issue by colin-axner** [cosmos/relayer#481]
Packets can disable usage of a timeout height by setting the revision number and height both to 0. 

The relayer was never architected to support revision numbers. The revision number feature was added fairly last minute to IBC. A lot of places assume the [existence](https://github.com/cosmos/relayer/blob/76eb658fb20a872b002ac4a523ac14f649132937/relayer/msgs.go#L378) of a timeout height. State based relaying needs to obtain the timeout in the revision form when parsing past txs, instead of only parsing the revision height and assuming the revision number based on chain-id

Alternatively, a quicker fix is to add a check if the timeout height is 0 and set the revision number to 0 as well

I'm not sure if relaying based on streaming accounts for this.

**Comment by seantking** [comment]
Setting both height & revision number to 0 causes the relayer to error for me. 

```
timeoutHeight := clienttypes.Height{
    RevisionNumber: 0,
    RevisionHeight: 0,
}
```
