### ISSUE TITLE
Remove dependency on Tendermint light client

### ISSUE THREAD

**Issue by colin-axner** [cosmos/relayer#493]
The light client isn't actually verifying the proofs returned from the full node. It is being used to get the headers to use the previous validator set. We should be using the full node to get the past headers and proof

If desirable, we could verify proofs with the light client before submitting them on chain. But given the current strategy of this relayer, I'd prefer to see the light client removed for now

Not something that needs to be addressed. Just food for thought

**Comment by colin-axner** [comment]
In general, it should be possible to run a relayer without initializing a light client

**Comment by jackzampolin** [comment]
We done did the thang mr thang
