### ISSUE TITLE
Relayer version for v1.0.0 of ibc-go

### ISSUE THREAD

**Issue by jackzampolin** [cosmos/relayer#513]
cc @colin-axner

**Comment by colin-axner** [comment]
Please continue work off of this [pr](https://github.com/cosmos/relayer/pull/501)

**Comment by colin-axner** [comment]
Also see the [migration docs](https://github.com/cosmos/ibc-go/blob/main/docs/migrations/ibc-migration-043.md) on ibc-go

**Comment by jackzampolin** [comment]
We even have IBC v2.0.0 now 😉
