### ISSUE TITLE
Segmentation violation while following README

### ISSUE THREAD

**Issue by cryptophonic** [cosmos/relayer#53]
Getting the following error about 1/2 way down the README instructions

$ rly tx full-path demo-path
I[2020-03-24|15:38:42.463] ✘ [ibc0]@{0} - msg(0:create_client) err(sdk: tx parse error) 
I[2020-03-24|15:38:42.476] ✘ [ibc1]@{0} - msg(0:create_client) err(sdk: tx parse error) 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0xe6b065]

goroutine 1 [running]:
github.com/iqlusioninc/relayer/relayer.(*Chain).CreateConnectionStep(0xc000e7c480, 0xc000e7c6c0, 0x0, 0x0, 0x0)
	/home/mjackson/iqlusion/relayer/relayer/tx.go:147 +0x4b5
github.com/iqlusioninc/relayer/relayer.(*Chain).CreateConnection(0xc000e7c480, 0xc000e7c6c0, 0x2540be400, 0x4, 0xc000e983d0)
	/home/mjackson/iqlusion/relayer/relayer/tx.go:79 +0x84
github.com/iqlusioninc/relayer/cmd.fullPathCmd.func1(0xc000e4a840, 0xc000e700d0, 0x1, 0x1, 0x0, 0x0)
	/home/mjackson/iqlusion/relayer/cmd/tx.go:190 +0x39d
github.com/spf13/cobra.(*Command).execute(0xc000e4a840, 0xc000e70090, 0x1, 0x1, 0xc000e4a840, 0xc000e70090)
	/home/mjackson/iqlusion/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:840 +0x453
github.com/spf13/cobra.(*Command).ExecuteC(0x1ee5f40, 0x44563a, 0x1e796c0, 0xc000000180)
	/home/mjackson/iqlusion/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:945 +0x317
github.com/spf13/cobra.(*Command).Execute(...)
	/home/mjackson/iqlusion/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:885
github.com/iqlusioninc/relayer/cmd.Execute()
	/home/mjackson/iqlusion/relayer/cmd/root.go:98 +0x55
main.main()
	/home/mjackson/iqlusion/relayer/main.go:21 +0x20

**Comment by cryptophonic** [comment]
$ gaiad version
0.0.0-243-ga9aa9ea

$ rly version
version: 0.1.0-60-g157637b
commit: 157637bf44536a2b4856ed7d779f7c62b6a1dd93
cosmos-sdk: v0.34.4-0.20200318160616-b8295506615b
go: go1.14 linux/amd64

**Comment by cryptophonic** [comment]
seems to be fixed with the latest build / master branch

**Comment by dryruner** [comment]
@mjackson001 I'm still seeing the same error with latest build :( :

$ rly version
version: 0.1.0-75-g717f5d0
commit: 717f5d04306fa053bcf949ad1906ccdb8bb8ccea
cosmos-sdk: v0.34.4-0.20200324184639-0ed9ed648788
go: go1.14 darwin/amd64

**Comment by cryptophonic** [comment]
I was able to get it to work here on the latest code this morning.  Reopening for more information but it does seem to work here.

**Comment by cryptophonic** [comment]
This morning the build is not working, failing with a similar error.  The logs seem to indicate some sort of a transaction timeout.

```
I[2020-03-28|09:27:51.872] - [ibc1] CONTAINER AVAILABLE AT PORT http://localhost:33167 
I[2020-03-28|09:27:54.272] - [ibc0] CONTAINER AVAILABLE AT PORT http://localhost:39179 
E[2020-03-28|09:28:01.614] - [ibc0] -> err(broadcast_tx_commit: Post failed: Post "http://localhost:39179": context deadline exceeded (Client.Timeout exceeded while awaiting headers)) 
E[2020-03-28|09:28:04.647] - [ibc1] -> err(broadcast_tx_commit: Post failed: Post "http://localhost:33167": context deadline exceeded (Client.Timeout exceeded while awaiting headers)) 
I[2020-03-28|09:28:07.923] - [ibc1] SPUN DOWN CONTAINER /ibc1-TestRelayUnRelayedPacketsOnOrderedChannel from jackzampolin/gaiatest:jack_relayer-testing 
I[2020-03-28|09:28:09.971] - [ibc0] SPUN DOWN CONTAINER /ibc0-TestRelayUnRelayedPacketsOnOrderedChannel from jackzampolin/gaiatest:jack_relayer-testing 
--- FAIL: TestRelayUnRelayedPacketsOnOrderedChannel (32.07s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0xff0553]

goroutine 222 [running]:
testing.tRunner.func1.1(0x112b960, 0x1f03100)
        /usr/local/go/src/testing/testing.go:941 +0x3d0
testing.tRunner.func1(0xc001252c60)
        /usr/local/go/src/testing/testing.go:944 +0x3f9
panic(0x112b960, 0x1f03100)
        /usr/local/go/src/runtime/panic.go:967 +0x15d
github.com/iqlusioninc/relayer/relayer.(*Chain).CreateConnectionStep(0xc001252d80, 0xc001252ea0, 0x1439ee0, 0xc001252c60, 0xc001557c60)
        /home/mjackson/microtick/ibc/relayer/relayer/tx.go:147 +0x573
github.com/iqlusioninc/relayer/relayer.(*Chain).CreateConnection(0xc001252d80, 0xc001252ea0, 0xb2d05e00, 0x0, 0x0)
        /home/mjackson/microtick/ibc/relayer/relayer/tx.go:79 +0x98
github.com/iqlusioninc/relayer/relayer.TestRelayUnRelayedPacketsOnOrderedChannel(0xc001252c60)
        /home/mjackson/microtick/ibc/relayer/relayer/relayer_test.go:88 +0x65b
testing.tRunner(0xc001252c60, 0x1437958)
        /usr/local/go/src/testing/testing.go:992 +0xdc
created by testing.(*T).Run
        /usr/local/go/src/testing/testing.go:1043 +0x357
FAIL    github.com/iqlusioninc/relayer/relayer  72.977s
FAIL
make: *** [Makefile:46: ci-test] Error 1
```

**Comment by jackzampolin** [comment]
I'm pretty sure this was due to queries for transactions returning bad data. I've added retries and safety checks here. Going to go ahead and close the issue.
