### ISSUE TITLE
Refactor relayer cosmos provider to use lens

### ISSUE THREAD

**Issue by jackzampolin** [cosmos/relayer#537]
https://github.com/strangelove-ventures/lens/

**Comment by jackzampolin** [comment]
Major features from lens:
- new broadcast mode to block on transaction till last one is accepted https://github.com/strangelove-ventures/lens/issues/12
- better bech32 handling should eliminate the dreaded bech32 errors

**Comment by boojamya** [comment]
Lens is now a dependency in relayer.
