### ISSUE TITLE
Using the same seed for source and dest accounts of a path result in an error

### ISSUE THREAD

**Issue by franono** [cosmos/relayer#539]
I experienced this whilst creating an IBC connection between juno and osmosis testnets. The config is set with account-prefix juno and osmo respectively, as below.

When I run `rly tx link <path>` I either get `rpc error: code = InvalidArgument desc = invalid Bech32 prefix; expected juno, got osmo: invalid request` or the other way round. It seems like it's using the same prefix for both chains, which is fixed when the keys used are not the same seed.

`global:
  api-listen-addr: :5183
  timeout: 10s
  light-cache-size: 20
chains:
- key: uni-key
  chain-id: uni
  rpc-addr: http://XXX:26657/
  account-prefix: juno
  gas-adjustment: 1.5
  gas-prices: 1.0ujunox
  trusting-period: 24h
- key: osmo-key2
  chain-id: osmosis-clean-testnet-X
  rpc-addr: http://XX:26657/
  account-prefix: osmo
  gas-adjustment: 1.5
  gas-prices: 0.1uosmo
  trusting-period: 24h
paths:
  transfer:
    src:
      chain-id: uni
      client-id: 07-tendermint-41
      connection-id: connection-36
      channel-id: channel-36
      port-id: transfer
      order: UNORDERED
      version: ics20-1
    dst:
      chain-id: osmosis-clean-testnet-X
      client-id: 07-tendermint-2
      connection-id: connection-2
      channel-id: channel-0
      port-id: transfer
      order: UNORDERED
      version: ics20-1
    strategy:
      type: naive`

**Comment by jtieri** [comment]
We are currently in the midst of a major refactor to the relayer which will ultimately result in a v2 line being cut soon (hopefully this week). Part of the work that we have been undertaking *SHOULD* kill the bech32 issues that are currently present in the relayer.

Thanks for opening an issue @franono we do appreciate it!

**Comment by jtieri** [comment]
This should be fixed as of #578 where we squashed the bech32 errors by avoiding certain calls in the SDK and by utilizing `lens`

Closing this
