### ISSUE TITLE
Integration tests

### ISSUE THREAD

**Issue by jackzampolin** [cosmos/relayer#54]
The current plan is to test the `relayer` package using something like https://github.com/ory/dockertest and a gaia image that allows for passing in addresses to be funded for genesis. Will work on getting this setup.

**Comment by jhernandezb** [comment]
I can help with this as well

**Comment by jackzampolin** [comment]
@jhernandezb I've got an approach here https://github.com/iqlusioninc/relayer/pull/58 going to clean this up this afternoon. What do you think?

**Comment by jackzampolin** [comment]
This is implemented and working.
