### ISSUE TITLE
QoS Reporting

### ISSUE THREAD

**Issue by boojamya** [cosmos/relayer#551]
Copying over from Strangelove repo: [LINK](https://github.com/strangelove-ventures/relayer/issues/30)

As a user I should be able to query for the quality of service on a given channel over a given time period:

```
# Query quality of service over the last day
$ rly q quality-of-service {path} --since 1d

# Query quality of service over a given time period
$ rly q qos {path} --start "2021-08-29 10:00:00" --end "2021-08-29 13:00:00"

# use time.Parse("2006-01-02 15:04:05", date) to parse input
```
This should do a transaction search for MsgTransfer on each chain and also for MsgRecvPacket and MsgTimeoutPacket to compare the numbers for a given time period.

This is already implemented [here](https://github.com/strangelove-ventures/relayer/blob/main/cmd/etl.go)
Consider cleaning up or moving into its own repo as we progress with lens.

**Comment by jtieri** [comment]
Closing this because we are going to build out a standalone solution for indexing data across the interchain.
