### ISSUE TITLE
New channel creation should be documented

### ISSUE THREAD

**Issue by boojamya** [cosmos/relayer#553]
Moved over from Strangelove Repo.
https://github.com/strangelove-ventures/relayer/issues/45

@faddat

Link Command function:
https://github.com/strangelove-ventures/relayer/issues/45

**Comment by jtieri** [comment]
Tried helping the Kava team open new paths this morning for Kava<->Cosmos Hub and ran into several issues.

After adding the configuration information for Kava to the relayer config and running `rly tx link kavahub` the relayer spits out this error. 

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x1203996]

goroutine 1 [running]:
github.com/cosmos/relayer/cmd.(*Config).ChainsFromPath(0x13125a0, {0x7ffef0926361, 0x7})
	/home/anon/go/src/github.com/cosmos/relayer/cmd/config.go:432 +0x36
github.com/cosmos/relayer/cmd.linkCmd.func1(0xc000f7cf00, {0xc000f5be40, 0x1, 0x1})
	/home/anon/go/src/github.com/cosmos/relayer/cmd/tx.go:364 +0xc8
github.com/spf13/cobra.(*Command).execute(0xc000f7cf00, {0xc000f5be20, 0x1, 0x1})
	/home/anon/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:856 +0x60e
github.com/spf13/cobra.(*Command).ExecuteC(0xc000f62500)
	/home/anon/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
	/home/anon/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:902
github.com/cosmos/relayer/cmd.Execute()
	/home/anon/go/src/github.com/cosmos/relayer/cmd/root.go:107 +0x31
main.main()
	/home/anon/go/src/github.com/cosmos/relayer/main.go:6 +0x17
```

From a naive glance, it would appear that there is some issue with the new config format when trying to fetch the chains from the config. Gonna run through this process several times from various starting points and add some more context here as we try to standardize this process and make it not only more clear but incredibly easy for users.

**Comment by jtieri** [comment]
After some discussion with @jackzampolin it seems like a good flow for creating new paths between chains will look something like the following.

- Users generate a new empty path via `rly paths new [src-chain-id] [dst-chain-id] [path-name] [flags]`
- Users link the paths via `rly tx link [path-name]`
- Users are now ready to relay against the new path

This would allow the user to setup new paths straight from the command line without having to manage/edit any files manually. It also abstracts the process away from the user such that `link` "just works" and leaves the user in a state where they can relay without having to put much thought into the generation of identifiers.

**Comment by jtieri** [comment]
We have a clear workflow for creating new paths between zones now, we just need to create some clear documentation that will be added to the README or in a separate document in `docs/`

**Comment by boojamya** [comment]
Closing.
https://github.com/cosmos/relayer/pull/615
