### ISSUE TITLE
Interchain accounts testing

### ISSUE THREAD

**Issue by boojamya** [cosmos/relayer#555]
Interchain account supports needs testing in Relayer. 

This may or may not need to be addressed also:
https://github.com/strangelove-ventures/relayer/issues/48

**Comment by jtieri** [comment]
ibc-go v3 beta release has been [cut](https://github.com/cosmos/ibc-go/releases/tag/v3.0.0-beta1) so we need to spend some time testing Interchain Accounts

We need to create some documentation for users that indicated which versions of ibc-go are compatible with the various versions of the relayer

"... update its release notes to display which versions are compatible/have been tested against which versions of ibc-go"

**Comment by jtieri** [comment]
Interchain Accounts (IA) require relayers to initialize the client and connection handshakes and then wait for the IA module command `intertx register` to start the channel handshake. Relayers should listen for the `ChannelOpenInit` event and then finish the channel handshake to see that the IA is successfully created on the host chain and registered as an active channel in state.

Upon successful creation of the IA account on the controller chain a `port-id` will be dynamically generated which looks like:
`icacontroller-{owner-account-address}` 

The `port-id` on the host chain will then be `icahost`

So the flow for creating an IA will look something like
1. Controller chain emits event from `intertx register`
2. Relayer listens for `ChannelOpenInit` and then proceeds to finish the channel handshake
3. During `OnChanOpenTry` on the host chain an IA is registered and the IA address is mapped to the owner acc address and stored in state
4. During `OnChanOpenAck` on the controller chain a record of the IA previously registered is set in the state with a mapping of `port-id` to IA address
5. During the `OnChanOpenAck` & `OnChanOpenConfirm` on the controller & host chains respectively, the [active-channel](https://github.com/cosmos/ibc/blob/master/spec/app/ics-027-interchain-accounts/README.md#Active-channels) for this interchain account/owner pair, is set in state.

See: [ics-27 spec](https://github.com/cosmos/ibc/blob/master/spec/app/ics-027-interchain-accounts/README.md#identifier-formats) 

So ultimately the go-relayer needs to be able to listen for channel handshake events on a given connection. This ties back into #573 where we need to switch to a connection based relaying model. Switching to this new connection based relaying model is now preliminary work necessary for ensuring IA works with the go-relayer
