### ISSUE TITLE
Two different ways to add chains and paths

### ISSUE THREAD

**Issue by boojamya** [cosmos/relayer#560]
NOTE: Relevant to this PR: https://github.com/cosmos/relayer/tree/justin/use-chain-registry

1. `rly chains add`
2.` rly config add-chains`

Do we want to keep both of these options of adding chains and paths?

**Comment by boojamya** [comment]
Paths:

1. `rly config add-paths`
2. `rly paths add`
3. `rly paths fetch`

**Comment by jtieri** [comment]
Maybe the `rly chains add` and `rly config add-chains` should just be one command versus having the same functionality in two places.

For the paths cmds, `rly paths add` allows a user to specify a file to be added to the configuration (this is the same as `rly config add-paths` so maybe we also make this one command) but `rly paths fetch` is the automated command that does not allow a user to specify a custom path config file but instead fetches the paths for each chain currently configured that has metadata in `interchain/` directory
