### ISSUE TITLE
Do can connectt IBC relayer with Ethermint chain?

### ISSUE THREAD

**Issue by hoang14x** [cosmos/relayer#586]

**Comment by boojamya** [comment]
Yes, since Ethermint is built on Cosmos SDK this should be possible. 

You will need the relevant Ethermint chain-meta data. 
Unfortunately, I do not see anything in the [chain-registry](https://github.com/cosmos/chain-registry).

**Comment by hoang14x** [comment]
hi @boojamya 
I have this case.
I use cosmos/relayer to connect 2 chain
chain 01: use cosmos/hub (https://github.com/cosmos/gaia)
chain 02: ethermint chain

both chain setup at local
i have a error
` rly tx link path -d -o 3s --home gaid1`

error: 
Error: error creating clients. Err: failed to create client on dst chain{sentry_9000-1}. Err: please ensure provided on-chain client (07-tendermint-0) exists on the chain (sentry_9000-1): 07-tendermint-0: light client not found [/Users/lap02139/Documents/Work2/relayer/relayer/provider/cosmos/query.go:176]

 rly start path -d --home gaid1
 
 error:
E[2022-03-08|10:21:03.507] - [ibc-0] -> err(rpc error: code = InvalidArgument desc = failed to execute message; message index: 0: cannot update client with ID 07-tendermint-0: trusted validators validators:<address:"v\327\205\242\010\235\3523\004=\034#\342$\262\013i\241\034G" pub_key:<ed25519:"\013\345\020\350\007?\376$\334\177\207Y\033\313&\325E\270\004E\201\327\000\346\234\336\023\334&\3128~" > voting_power:1000000000000000 > proposer:<address:"v\327\205\242\010\235\3523\004=\034#\342$\262\013i\241\034G" pub_key:<ed25519:"\013\345\020\350\007?\376$\334\177\207Y\033\313&\325E\270\004E\201\327\000\346\234\336\023\334&\3128~" > voting_power:1000000000000000 > , does not hash to latest trusted validators. Expected: 27C5B7085C5622D0A2EAAC8209E30D091073D05DA9A10D98A3C7A41A7BB7B08E, got: 5784F2DC724A9AEE9E71A1CE5D84CE1845666B8DC82E65DBE13071CC158E229A: invalid validator set: invalid request) 
I[2022-03-08|10:21:04.971] update clients error. Err: 07-tendermint-0: light client not found [/Users/lap02139/Documents/Work2/relayer/relayer/provider/cosmos/query.go:176] 
^CSignal Received interrupt

Are you know this error?
