### ISSUE TITLE
relayer restore key surpport cointype 60

### ISSUE THREAD

**Issue by Ywmet** [cosmos/relayer#588]
when import mnemonic using cointype 118 ,we will get another Address diff from 60. 
Now oec want to add ibc ,but using cointype 60,relayer could not generate the address that oec Identified. 
Suggest Add relayer command to specify the cointype eg:60 and algo eg:secp256k1. 
thx!

**Comment by hoang14x** [comment]
save my issue.
address generate from ethermint is different with relayer generate

**Comment by boojamya** [comment]
The flag ` --coin-type` is not currently wired up to anything and Coin-type 118 is hard coded throughout.

It may be worth looking using Lens to restore keys inside of the Relayer.

**Comment by jtieri** [comment]
This should be fixed in the linked PR!

Thanks for opening the issue.
