### ISSUE TITLE
"rly light init" not supported anymore?

### ISSUE THREAD

**Issue by Red-Blink** [cosmos/relayer#592]
**Using v1.0.0**

When I perform `rly chains list`, key, bal and path are ticked, but light is X.

When I do `rly light init columbus-5`, I receive unknown command "light" for "rly".

What to do in this case?

**Comment by meetrick** [comment]
Hi bro, 
```rly light```command is not used in latest version.
You don't need ```rly light init``` for relayer initialization.

**Comment by boojamya** [comment]
Yes, `rly light init` is not not supported. 
@D3vJohn, Checkout from main and then `make install`

When using `rly chains list`, I believe "light" has been replaced with "path"

You can easily add chains to your config by using `rly chains add [[chain-name]]` 
The chain will now be configured.

**Comment by Red-Blink** [comment]
> Yes, `rly light init` is not not supported. @D3vJohn, Checkout from main and then `make install`
> 
> When using `rly chains list`, I believe "light" has been replaced with "path"
> 
> You can easily add chains to your config by using `rly chains add [[chain-name]]` The chain will now be configured.

`rly chains list` shows the chains along to their **key, bal, light, path.**

So if `light` was replaced by `path`, then it should be removed from the `rly chains list`

That's what confused me actually!

**Comment by boojamya** [comment]
@D3vJohn, I was partially incorrect. 

`light` wasn't really replace by `path`...
`light` used to be used to verify the local light client which is not needed in current versions of relayer.
If `path` is valid, it is my understanding that  ID's for client, connection and channel should also be valid.
