### ISSUE TITLE
Unhandled connection and channel state case

### ISSUE THREAD

**Issue by ancazamfir** [cosmos/relayer#6]
A few first observations after trying the relayer commands. 

- many IDs local to `ibc0` are of form `ibcone<item>` which for me intuitively meant `<item> on chain ibc1`. Maybe `<item>toibc1`...like `connectiontoibc1`,  or `connAtoB`, etc if this is a connectionID with `ibc0/ A` scope (see [demo json files](https://github.com/iqlusioninc/relayer/tree/master/demo))

- the `query connections` command doesn't return local `connection ID`:
```
$ relayer query connections ibc0
[{"state":"OPEN","client_id":"ibconeclient","counterparty":{"client_id":"ibczeroclient","connection_id":"ibczeroconnection","prefix":{"type":"ibc/commitment/MerklePrefix","value":{"key_prefix":"aWJj"}}},"versions":["1.0.0"]}]
```
With multiple connections it's going to be hard to figure out the ID to query a given connection on a chain, `ibc0` in this case

- ditto for channels, `query channels` doesn't return local channel ID

- error numbers are shown on SDK failures, hard to determine what is going on

- looking at SDK connection handlers, it seems that both ends can be in `INIT` state and `ConnOpenTry` relayed to either end would still progress the handshake (rhis is not the case in the IBC specification). However the relayer does not relay for this case. Same for channel.

[I will collect more here]

**Comment by jackzampolin** [comment]
Opened https://github.com/cosmos/cosmos-sdk/issues/5829 to address the lack of local identifiers.

**Comment by ancazamfir** [comment]
Also, was trying to figure out if we can easily demo loopback connection, channel, etc. using relayer commands. It seems that a few commands will need to change to handle same source and dest chains and single client. 
Have you looked at that?

**Comment by jackzampolin** [comment]
@ancazamfir I've substantially refactored the relayer and it should be able to handle the loopback case. Might be a couple of small errors but I don't think it should be an issue. The loopback client just landed in the SDK so would be cool to test it. As for your original issue I think I've addressed pretty much everything there except the unhandled connection and channel handshake cases. I'll leave this issue open to address that.

**Comment by ancazamfir** [comment]
re: loopback
I am not sure how the loopback connection should be configured. I tried a number of things:

1) configure a single connectionend with counterparty having the same connectionId as local
```
rly tx raw client ibc0 ibc0 loopbackclient
rly tx raw conn-init ibc0 ibc0 loopbackclient loopbackclient loopconnsrc loopconnsrc
rly tx raw conn-try ibc0 ibc0 loopbackclient loopbackclient loopconnsrc loopconnsrc
rly tx raw conn-ack ibc0 ibc0 loopbackclient loopbackclient loopconnsrc loopconnsrc
```
On the `conn-ack` I see:

```
{"height":"119","txhash":"50888B8DFB26F4B209F61F1F8D60B579105DCBCD8102C3D41802BE1ABC3081BC","codespace":"connection","code":5,"gas_wanted":"200000","gas_used":"104852"}
```
I believe this is caused by this in the connection handler:
```
	// Check connection on ChainA is on correct state: INIT
	if connection.State != exported.INIT {
		return sdkerrors.Wrapf(
			types.ErrInvalidConnectionState,
			"connection state is not INIT (got %s)", connection.State.String(),
		)
	}
```
We should allow also `exported.TRYOPEN`

There is an issue for SDK that mentions this, see #4 in https://github.com/cosmos/cosmos-sdk/issues/5908


2) configured two connection ends,`loopconnsrc` and `loopconndest`, and then continue like in the case of separate chains. This one now fails in conn-try
```
rly tx raw client ibc0 ibc0 loopbackclient
rly tx raw conn-init ibc0 ibc0 loopbackclient loopbackclient loopconnsrc loopconndst
rly tx raw conn-try ibc0 ibc0 loopbackclient loopbackclient loopconndst loopconnsrc
```
On the `conn-try` I see:
```
{"height":"0","txhash":"DF9A6CD07663C5E1F38F971D90D71EF686041112ADE8CDCEF3CADDD879DE70FC","codespace":"commitment","code":1}
```
It might fail here but not entirely sure:
```
func (msg MsgConnectionOpenTry) ValidateBasic() error {
...
	if msg.ProofHeight == 0 {
		return sdkerrors.Wrap(ibctypes.ErrInvalidHeight, "proof height must be > 0")
	}
	if msg.ConsensusHeight == 0 {
		return sdkerrors.Wrap(ibctypes.ErrInvalidHeight, "consensus height must be > 0")
	}
```

3) Then I tried the same as 2 but init both ends, fails in conn-ack:
```
rly tx raw client ibc0 ibc0 loopbackclient
rly tx raw conn-init ibc0 ibc0 loopbackclient loopbackclient loopconnsrc loopconndst
rly tx raw conn-init ibc0 ibc0 loopbackclient loopbackclient loopconndst  loopconnsrc

rly tx raw conn-try ibc0 ibc0 loopbackclient loopbackclient loopconndst loopconnsrc
rly tx raw conn-ack ibc0 ibc0 loopbackclient loopbackclient loopconnsrc loopconndst
```
On the `conn-ack` I see:
```
{"height":"661","txhash":"E94E8AEC02BF3B1B4D1B10B8542F5F25CE6B3793B7C21A58CFB37E35C4A3866E","codespace":"client","code":14,"gas_wanted":"200000","gas_used":"113125"}
```
I believe this fails in the loopback client here:
```
func (cs ClientState) VerifyConnectionState(
	cdc *codec.Codec,
	_ uint64,
	prefix commitmentexported.Prefix,
	_ commitmentexported.Proof,
	connectionID string,
	connectionEnd connectionexported.ConnectionI,
	_ clientexported.ConsensusState,
) error {
...
	if connectionEnd != prevConnection {
		return sdkerrors.Wrapf(
			clienttypes.ErrFailedConnectionStateVerification,
			"connection end ≠ previous stored connection: \n%v\n≠\n%v", connectionEnd, prevConnection,
		)
	}

...
}
```

**Comment by ancazamfir** [comment]
An update on this, the relayer seems to create a tendermint client on `rly tx raw client ibc0 ibc0 loopbackclient`. Should it create a loopback client if src, dest chains are the same. @jackzampolin?

**Comment by jackzampolin** [comment]
Closing this issue as addressed! 🎉
