### ISSUE TITLE
Add ability to send on local chain

### ISSUE THREAD

**Issue by jackzampolin** [cosmos/relayer#60]
This is for sending tokens between two accounts.

**Comment by jtieri** [comment]
Was jumping through the codebase today and realized this functionality was baked into the relayer but is commented out now. 

https://github.com/cosmos/relayer/blob/0b70e20873165e3fed7f84730cb4672aa07888cf/cmd/tx.go#L55-L102

Adding it back in as is would not be an issue but this would only work for Cosmos SDK based chains. Making it work for non-Cosmos chains could be achieved by adding an additional function to the `Provider` interface, something like `NewMsgSend` which constructs an msg for sending funds on the same chain vs. over IBC.
