### ISSUE TITLE
provider configuration for testing

### ISSUE THREAD

**Issue by oshorefueled** [cosmos/relayer#636]
Declaring a provider configuration requires using the cosmos.CosmosProviderConfig for testing https://github.com/cosmos/relayer/blob/main/_test/test_chains.go#L70. Will there be a more general type defined for this? Or a separate test setup should be created for other chain providers.

**Comment by jtieri** [comment]
Opened a PR for this here https://github.com/cosmos/relayer/pull/709

This should allow you guys to create your own `ProviderConfig` type to be used in the integration tests. 

You would just need to add a case to this type switch and handle the overwriting of the key and RPC address like we are currently doing.  https://github.com/cosmos/relayer/blob/703c0223277cfb3f24fe82ec8cd3784f254ff68b/_test/test_chains.go#L122-L134

There is still one blocker for fully integrating with the tests which I mention in the PR. Shouldn't be a hard task just need to implement some logic for spinning up a Substrate chain and perform a check on the `Provider` type to handle spinning up the chain appropriately.

https://github.com/cosmos/relayer/blob/703c0223277cfb3f24fe82ec8cd3784f254ff68b/_test/test_setup.go#L57
