### ISSUE TITLE
feat: add optional `--trusting-period` flag for client initialization 

### ISSUE THREAD

**Issue by jtieri** [cosmos/relayer#639]
Currently we dynamically set the trusting period by querying the unbonding time for a chain and using a value that is 85% of said unbonding time.

As a user, it may be desirable to have a way to manually set the trusting period during client initialization. 
The flag would be added to every command used for client creation and then passed down into the `CreateClients()` and `CreateClient()` calls.

**Comment by boojamya** [comment]
This is implemented: https://github.com/cosmos/relayer/pull/869
