### ISSUE TITLE
How to fix "rly tx link [paths-name]" Errors.

### ISSUE THREAD

**Issue by wlsaud619** [cosmos/relayer#64]
The following error occurs when 'rly tx link [path-name]' command is used after setting paths in some validators.
```
$ rly tx link achain_pylonchain
I[2020-03-27|13:29:47.131] ✘ [achain]@{0} - msg(0:create_client) err(sdk: tx parse error)
I[2020-03-27|13:29:47.524] ✘ [pylonchain]@{0} - msg(0:create_client) err(sdk: tx parse error)
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0xf6bdee]
```

### Solution.
Install the latest versions of **gaiad** and **relayer** for `gaiad.service` and `faucet.service` and restart.

After applying the solution, I checked that the information in my chain is coming out correctly.
However, the problem remains because the other party's chain is not updated.
In order to solve the issue, it seems that all validators need to update gaiad and relayer.
```
$ rly tx link achain_pylonchain
I[2020-03-27|17:52:37.942] ✔ [achain]@{374} - msg(0:create_client) hash(76DD51C120D07A629C2B278CA7A7A7145D096BE41E207CFC310101FBDDA64189)
I[2020-03-27|17:52:38.404] ✘ [pylonchain]@{0} - msg(0:create_client) err(sdk: tx parse error)
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0xf6be48]

```

### Updated version.
```
$ gaiad version
0.0.0-244-g276e9b7
```

```
$ rly version
version: 0.1.0-77-g66162a7
commit: 66162a7c8b55136b7aac478034329fd07818fd07
cosmos-sdk: v0.34.4-0.20200324184639-0ed9ed648788
go: go1.14 linux/amd64
```

**Comment by jackzampolin** [comment]
@wlsaud619 that is correct, please expect breaking changes during the alpha releases. This issue will not be present in the GoZ software.

**Comment by jackzampolin** [comment]
I've updated my node and the clients create successfully, but it looks like you are pruning old states on your node. You need to be running with `--pruning=nothing`
