### ISSUE TITLE
cmd `rly keys export` use the `DefaultKeyPass `  is not clear

### ISSUE THREAD

**Issue by tpkeeper** [cosmos/relayer#646]
https://github.com/cosmos/relayer/blob/f8a02616087510da65715872292ef323613f78aa/cmd/keys.go#L302

**Comment by boojamya** [comment]
Hi @tpkeeper, thanks for the issue. 
Can you elaborate on what is not clear?

**Comment by tpkeeper** [comment]
I don't know the password `12345678` before i

**Comment by tpkeeper** [comment]
I want to export the private key and then import to another different wallet.
But it print decrypt error, because I don't know the password `12345678` before i review the code.

**Comment by boojamya** [comment]
Closing. 
Mnemonic needed to import or restore a key. We may consider removing the `rly keys export` command.
