### ISSUE TITLE
Properly check relayers funds for fees and make sure gas settings are correct

### ISSUE THREAD

**Issue by jtieri** [cosmos/relayer#693]
Today when we were trying to bring back IBC light clients for Juno we noticed that if a packet doesn't have proper gas settings, the relayer will hang in the call to `(*ChainClient).BroadcastTx()` inside of `(*CosmosProvider).SendMessages()`

We probably want to check out `(*CosmosProvider).CalculateGas()` and make sure it's working as intended. Some test cases around this would be helpful

We should also make sure that we are checking the relayers funds and if there aren't enough to pay the fees we return an error as early as possible.

**Comment by boojamya** [comment]
Closing. Will re-open if issue re-occurs.

**Comment by jtieri** [comment]
Re-opening this because I have confirmed that if you attempt to send a tx that does not have sufficient gas settings, you get absolutely no error messages indicating what went wrong and can even end up in an infinite loop.

# Problem
The relayer can broadcast a tx successfully, at which point it will wait until receiving confirmation that the tx was included in a block. The issue is that once this tx is broadcast we don't check to see if the tx was rejected so, we can find ourselves waiting for the tx to be included in a block until the default timeout time is reached. 

https://github.com/strangelove-ventures/lens/blob/26dcf5a657c6411e0f229e6a9f4325e1166e108e/client/broadcast.go#L90-L104

When we try to create clients from the relayer we can find ourselves in an infinite loop where upon the default timeout being reached, we keep retrying to send the tx with the same gas settings which means that the tx will never be included in a block.

# Solution
I believe the solution for this issue is two fold. 

One, we need to ensure that the tx simulation/fee calculation is behaving as intended. I would assume that this code path should accurately simulate the tx such that the proper gas settings are set before the tx is actually broadcast. 

Two, we should determine if it is feasible to check if a tx is rejected after broadcasting it. This should be done before we try to wait for said tx to be included in a block.

Edit: looks like we need to check the `code` field on `ResultBroadcastTx` against some of the registered error codes found here https://github.com/cosmos/cosmos-sdk/blob/main/types/errors/errors.go#L73

**Comment by jtieri** [comment]
This should have been fixed long ago, closing
