### ISSUE TITLE
Two-Chainz silent failure on unconventional gaia setup

### ISSUE THREAD

**Issue by colin-axner** [cosmos/relayer#71]
When running `./two-chainz`, there will be a silent failure if the user does not have the `origin` remote setup (on their gaia repo) or has their `origin` remote pointing to a different repo (a fork) other than `github.com/cosmos/gaia`. It silently fails because the output is being directed to `/dev/null`

Unlikely scenario, but I figured I'd open an issue in case someone runs into this issue. One side effect of this failure is the `data/` directory not being created and filled.

**Comment by jackzampolin** [comment]
@colin-axner would love to see a PR to fix this issue! Also 👋 good to see you here!
