### ISSUE TITLE
Event pase will cover pre value, if multi `write_acknowledgement` event happened in one tx

### ISSUE THREAD

**Issue by tpkeeper** [cosmos/relayer#722]
https://github.com/cosmos/relayer/blob/457f2ed485463535ecd66369c45a22e957c99200/relayer/provider/cosmos/query.go#L99

if relayer send multi `MsgRecvPacket` in one tx, it will emit multi `write_acknowledgement` event. the code above will skip some `write_acknowledgement` event  and this will finally cause lots of ack packet not dealed.

**Comment by jtieri** [comment]
Ahh yeah I see what you mean. I had an incorrect mental model for how this needed to work 😣

I was thinking this should always be returning one tx and so the events would not have collisions but failed to account for the fact that a tx could have multiple overlapping events/attributes. 
https://github.com/cosmos/relayer/blob/457f2ed485463535ecd66369c45a22e957c99200/relayer/provider/cosmos/provider.go#L963-L971

A map is not the best choice here in that case. I'll take a look at this sometime this week and try to refactor it so events/attributes are not being squashed like they are rn.
