### ISSUE TITLE
`rly tx client` does not log the newly created `client-id`

### ISSUE THREAD

**Issue by boojamya** [cosmos/relayer#733]
The new client-id should be included in the `successful transaction` log.

Without it, you need to run a query on the tx-hash to find the new client-id.

CURRENT LOG:
```
info	Successful transaction	{"provider_type": "cosmos", "chain_id": "cosmoshub-4", "height": 10290813, "msg_types": ["/ibc.core.client.v1.MsgCreateClient"], "tx_hash": "6422F6A9A43CCDE701001F112D7098003351492A5EDE34B0FB9047949BA98965"}
```

**Comment by jtieri** [comment]
Did it overwrite the client id to the config file? Also, I think we do have a line that's logged for client, connection, & channel creation but it may be debug output only if you didn't see it.

**Comment by boojamya** [comment]
Ah yes, it did indeed overwrite the config. 
Didn't see it in debug though.
