### ISSUE TITLE
Look into timeout tests failing in `ibc-test-framework`

### ISSUE THREAD

**Issue by jtieri** [cosmos/relayer#739]

**Comment by DavidNix** [comment]
Can I get more detail or a way to duplicate this issue? Locally and on CI I haven't come across timeout tests failing or flakiness in ibctest. 

Timestamp timeout is not supported until the event bus refactor goes through. See https://github.com/strangelove-ventures/ibctest/pull/81

**Comment by jtieri** [comment]
I don't think this is applicable anymore so going to close this issue.
