### ISSUE TITLE
ibc relayer betweet Evmos and Evmos error

### ISSUE THREAD

**Issue by Jerome-XM** [cosmos/relayer#746]
I use two evmos chains to test ibc  

Run command  `rly  tx link path -d`
error : `no concrete type registered for type URL /ethermint.types.v1.EthAccount against interface *types.AccountI`

Evmos version 4.0.0   ethermint  version 0.15.0

**Comment by boojamya** [comment]
When you add or restore your key, are you specifying the correct `coin-type` 

Evmos is coin type 60 I believe?

**Comment by ItsFunny** [comment]
same issue 
i did 'rly keys restore evmos_9000-4 testkey "${mnemonic}" --coin-type 60'   at first 
and then i executed 'rly  tx link okc64-evmos-testnet -d -o 3s   --order unordered'
finally , it failed with the same output

**Comment by ItsFunny** [comment]
@boojamya  
hi , what should i do to solve this problem

**Comment by boojamya** [comment]
See https://github.com/cosmos/relayer/issues/748

Unfortunately, in its current form, the relayer is not compatible.
It will need to implement that `ethsecp256k1` spec as an optional flag. [(go-ethereum/crypto)](https://github.com/ethereum/go-ethereum/tree/master/crypto/secp256k1)

**Comment by boojamya** [comment]
I'm having trouble spinning up an evmos chain to test at the moment but maybe give that fork from disperze a shot.
Link: https://github.com/disperze/relayer/tree/ethermint

**Comment by ItsFunny** [comment]
> See #748
> 
> Unfortunately, in its current form, the relayer is not compatible. It will need to implement that `ethsecp256k1` spec as an optional flag. [(go-ethereum/crypto)](https://github.com/ethereum/go-ethereum/tree/master/crypto/secp256k1)

all right , i get it, i thought relayer has done this already  , and for now ,it seems i have to customize my own relayer  again to support evm account (i have done that before),
