### ISSUE TITLE
Re-add support for submitting misbehaviors

### ISSUE THREAD

**Issue by jtieri** [cosmos/relayer#750]
This code used to be present but was removed when refactoring the codebase to account for the `Provider` abstraction.

We should get this added back and finalize the methods signature https://github.com/cosmos/relayer/blob/2bf5c32f1882a427c8ca41131fc2fc5c406700f5/relayer/provider/provider.go#L90

Testing cases for this should be built out in the `ibctest` repo

**Comment by jtieri** [comment]
The code that used to be in place for submitting misbehaviors is here https://github.com/cosmos/relayer/blob/50534d4bdc8afe00c1903b797895c32602aa3b7b/relayer/misbehaviour.go#L19-L87

**Comment by ItsFunny** [comment]
When will it  be finished

**Comment by jtieri** [comment]
Closed by #1121
