### ISSUE TITLE
Parsing config file fails

### ISSUE THREAD

**Issue by jtieri** [cosmos/relayer#794]
After commit 2ca95265d379eeb3e2437cbca9846cbe33953f9e there appear to be errors around unmarshaling the config file from disk. So effectively the CLI is broken because every time a CLI command is run `initConfig` is called.

```
rly chains list
Error unmarshalling config: yaml: unmarshal errors:
  line 6: cannot unmarshal !!seq into map[string]*cmd.ProviderConfigYAMLWrapper
Error: yaml: unmarshal errors:
  line 6: cannot unmarshal !!seq into map[string]*cmd.ProviderConfigYAMLWrapper
```

**Comment by boojamya** [comment]
Just double checking. 
Did you re initialize your config? 

https://github.com/cosmos/relayer/blob/main/docs/config_migration.md

**Comment by jtieri** [comment]
> Just double checking. Did you re initialize your config?
> 
> https://github.com/cosmos/relayer/blob/main/docs/config_migration.md

Ahh I tried to just add the `chain-name` field to all the chains to avoid having to delete my config file since it was so big but didn't realize the chain names were required as keys instead of values. 

False alarm!
