### ISSUE TITLE
Unregistered interface crypto.isPublicKey_Sum

### ISSUE THREAD

**Issue by ItsFunny** [cosmos/relayer#797]
What I want to do is  trying create connection between the cosmos and the evmos mainnet 
But It failed with  'Unregistered interface crypto.isPublicKey_Sum' 

Besides: I create client successfully

**Comment by ItsFunny** [comment]
same issue : https://github.com/cosmos/relayer/issues/795

**Comment by boojamya** [comment]
Thanks for the issue. Closing. Tracking here: https://github.com/cosmos/relayer/issues/795
