### ISSUE TITLE
Add support for channel upgradeability 

### ISSUE THREAD

**Issue by jtieri** [cosmos/relayer#829]
IBC will be adding a channel upgrade feature that will execute in a separate handshake process, after a channel has been created initially, that the relayer must be able to handle. This will allow a channel to be upgraded for supporting new IBC features without completely abandoning the channel and creating a new one.

See: 
https://github.com/cosmos/ibc/blob/master/spec/core/ics-004-channel-and-packet-semantics/UPGRADES.md
https://github.com/cosmos/ibc-go/issues/1599

**Comment by boojamya** [comment]
Note: according to IBC-Go team, this is scoped for Q2 2023.

**Comment by akc2267** [comment]
allegedly slated to be in the next ibc-go release

**Comment by jtieri** [comment]
Closing this issue in favor of #1293
