### ISSUE TITLE
Use counterparty chain's specified merkle prefix

### ISSUE THREAD

**Issue by jtieri** [cosmos/relayer#830]
The IBC spec allows for custom merkle prefixes which are used in state verification. Currently we assume this prefix is always the default prefix `ibc` but to align with the spec we should be querying or retrieving this data from the counterparty chain.

Link to [spec](https://github.com/cosmos/ibc/blob/37ce173dc6542e2aa2732258245af421566c74c4/spec/core/ics-003-connection-semantics/README.md#data-structures):
```
The counterpartyPrefix field contains the prefix used for state verification on the counterparty chain associated with this connection. Chains should expose an endpoint to allow relayers to query the connection prefix. If not specified, a default counterpartyPrefix of "ibc" should be used.
```

It looks like this is only used during `ConnectionOpenInit` so should be a marginal change.

**Comment by jtieri** [comment]
Looks like Penumbra could be using a non-default merkle prefix in their IBC implementation so this may be higher priority than initially thought. 
https://github.com/penumbra-zone/penumbra/pull/1189

**Comment by avahowell** [comment]
Yes! I encountered this while working on the Penumbra relayer provider. Penumbra is using a non-default prefix, the prefix should be `PenumbraAppHash`.
