### ISSUE TITLE
Idea: Fund management

### ISSUE THREAD

**Issue by jackzampolin** [cosmos/relayer#839]
This is just an idea but it would be cool:

As a user I would like to deposit tokens into a relayer account once and then have the relayer automatically trade into the currencies needed to relay across the configured paths. The way this might work is users would deposit `osmo` into an `osmo1...` address and then the relayer would trade into `atom`, `axl` and `stars` to cover `atom<>osmo`, `osmo<>axl` and `atom<> stars` routes. The relayer would periodically make these trades from the origial `osmo1....` account to keep the accounts on the individual chains full and continuing to relay. There would be an alert that could output to slack/discord/configurable when the balance of the relayer got too low that would enable users to quickly refill the balance. It would also be nice if when the user wanted to stop relaying there was one command that could be run to return all funds to the original currency on osmosis into the original wallet.

**Comment by jonathanpberger** [comment]
@KyleMoser wanna take a crack at this one?

**Comment by akc2267** [comment]
on hold until hyperlane work is complete

**Comment by jtieri** [comment]
This ticket essentially gave birth to Cronmos.
