### ISSUE TITLE
Incorporate IBC application versioning into relayer

### ISSUE THREAD

**Issue by jackzampolin** [cosmos/relayer#84]
Currently we have the `ibc-app-version` hardcoded to `ics20-1` for all messages. This needs to be changed to allow for more dynamic input.

**Comment by cwgoes** [comment]
Yes; it would be nice to tie this into a standard metadata format for all IBC application-layer protocols.

Ref https://github.com/cosmos/ics/issues/413.

**Comment by jackzampolin** [comment]
Maybe we should have the chains emit the `ibc-app-version` as a tag so that this could be done dynamically on a per packet basis
