### ISSUE TITLE
Add recommended vm settings to docs

### ISSUE THREAD

**Issue by boojamya** [cosmos/relayer#852]
We should add some recommendations on specific settings to use when running the relayer in the cloud.

I think we could rename [node_pruning.md](https://github.com/cosmos/relayer/blob/main/docs/node_pruning.md)  file to "Recommended settings" and add info there.

**Comment by boojamya** [comment]
@danBryan DanB for 👀

**Comment by jtieri** [comment]
hey @boojamya i know you no longer work on rly but do you remember if we ever added anything like this?

**Comment by boojamya** [comment]
Hey @jtieri, I don't think we added anything extra. I believe the main intentions here were to add a little more clarity on how a nodes pruning settings can effect the relayer's ability to relay, specifically when it comes to relaying historical transactions. 

I think the linked document is sufficient and maybe even overkill as the default pruning settings are probably fine?
Feel free to close.
