### ISSUE TITLE
 error Failed to query packet acknowledgement commitments after max attempts

### ISSUE THREAD

**Issue by williamweb3** [cosmos/relayer#865]
When I use rly paths list, It's all ok, such like that:
0: abc_test_path        -> chns(✔) clnts(✔) conn(✔) (AbcChain<>TestChain)
 1: test_abc_path        -> chns(✔) clnts(✔) conn(✔) (TestChain<>AbcChain)

But when I use rly start path, I got the error with : error Failed to query packet acknowledgement commitments after max attempts {"channel_id": "channel-1", "port_id": "transfer", "attempts": 5, "error": "no error on QueryPacketUnrelayedAcknowledgements for AbcChain, however response is nil"}

**Comment by boojamya** [comment]
Please try using the `-p events` flag in your `rly start` command.

While this is still in testing, it is proving to be highly effective. We will make this style of processing the default in the near future. 

Please re-open if you are still having issues.
