### ISSUE TITLE
The `scripts/` folder should be cleaned up and organzied

### ISSUE THREAD

**Issue by boojamya** [cosmos/relayer#872]
Many of the these bash scripts are duplicates and/or can be replaced by `ibctest`

**Comment by jtieri** [comment]
I know Composable is using the bash scripts for testing right now so maybe we gut these once we get them over to `ibctest`?

**Comment by jackzampolin** [comment]
I think we should keep a basic script in there for quick iteration by developers. Just the OG `two_chainz` maybe.
