### ISSUE TITLE
Prometheus/Monitoring Wishlist

### ISSUE THREAD

**Issue by Golden-Ratio-Staking** [cosmos/relayer#877]
- wallet_balance
- ibc_acknowledgment_packets
- ibc_receive_packets
- ibc_timeout_packets

**Comment by sascha1337** [comment]
cc https://github.com/cosmos/relayer/pull/882

**Comment by boojamya** [comment]
Referencing: https://github.com/cosmos/relayer/issues/648

**Comment by boojamya** [comment]
Closing: https://github.com/cosmos/relayer/pull/882, https://github.com/cosmos/relayer/pull/963
