### ISSUE TITLE
README correction

### ISSUE THREAD

**Issue by jtieri** [cosmos/relayer#884]
The README still has a section that reads, "At minimum, this command will add two paths, in our case it will add one path from cosmoshub to osmosis and another path from osmosis to cosmoshub."

This is no longer true and should be removed.

Edit: We may want to do a good once over for the entire README and docs to ensure the rest of them are consistent with v2

**Comment by boojamya** [comment]
Fixed: https://github.com/cosmos/relayer/pull/890
