### ISSUE TITLE
New commands to interact with config file

### ISSUE THREAD

**Issue by boojamya** [cosmos/relayer#887]
Manual configuration with the config file is still needed to edit some parts of the config file. 
It would be nice to have built-in commands.

- [x] Change default key 
- [x] Edit path filters

Nice to have:
- [x] Edit RPC endpoints

**Comment by boojamya** [comment]
Path filters completed here: #1077

**Comment by vimystic** [comment]
Change default key added here : #1282  and  #1289

**Comment by vimystic** [comment]
Edit RPC endpoints added here : #1292
