### ISSUE TITLE
Sequence send not found

### ISSUE THREAD

**Issue by ronaldstoner** [cosmos/relayer#90]
My first test of two-chainz was successful, but having issues after retrying due to sequence send not found. I've closed and re-opened the channel, re-started both chains locally, verified balances, and initiated lite clients. I'm not sure what else I am missing. The following error occurs with both chains trying to transfer to each other. 

```stoner@stonerzone:~/iqlusion/relayer$ rly tx transfer ibc0 ibc1 10000n0token false $(rly keys show ibc1 testkey) [2020-04-14|12:20:10.690] ✘ [ibc0]@{56323} - msg(0:transfer) err(channels: sequence send not found) Error: failed to send first transaction```

**Comment by jackzampolin** [comment]
@ronaldstoner thanks for the report. If you are having issues please include full reproduction steps and run the commands with `-d`. This will include full output from the command including raw transaction data.

**Comment by weichang-x** [comment]
Same issue here:
```
rly tx transfer cosmoshub irishub 1000uatom true cosmos1zzcuqga83przn9lkfxzza6p5arftrhcmxwystc -d
I[2020-04-17|08:41:52.661] - [cosmoshub] -> sending transaction:
[{"type":"ibc/transfer/MsgTransfer","value":{"source_port":"transfer","source_channel":"cosmoshubchan","dest_height":"90159","amount":[{"denom":"transfer/irishubchan/uatom","amount":"1000"}],"sender":"cosmos12pnvxv2ee5ruvgykz2md46rhd5tkk29eqsvkn0","receiver":"cosmos1zzcuqga83przn9lkfxzza6p5arftrhcmxwystc"}}]
I[2020-04-17|08:41:52.662] ✘ [cosmoshub]@{89928} - msg(0:transfer) err(channels: sequence send not found)
{"height":"89928","txhash":"5C05F8B253BC6681107B48CCECA1AC1808EB032AF494D855DBD6A69B3AB02515","codespace":"channels","code":8,"raw_log":"failed to execute message; message index: 0: module does not own channel capability: channel capability not found","gas_wanted":"200000","gas_used":"46655"}
Error: failed to send first transaction
```

**Comment by ronaldstoner** [comment]
Resolving this as I have not been able to reproduce.
