### ISSUE TITLE
Error assembling channel messages

### ISSUE THREAD

**Issue by steveliupai** [cosmos/relayer#936]
![image](https://user-images.githubusercontent.com/3140474/186065988-b748935a-51f2-411e-afd5-61894cf917d9.png)

I was trying to run a relayer between lambda  testnet and osmosis testnet and it throw out an error like this, anything i can do to fix this?

**Comment by agouin** [comment]
This is a benign error. The channel handshake was completed by the `MsgChannelOpenConfirm` message, so it gave up on the next message it was processing since it had finished the task of the `tx link`.
