### ISSUE TITLE
`rly q txs` cmd appears to not work properly

### ISSUE THREAD

**Issue by jtieri** [cosmos/relayer#957]
A user reported that this command may be broken and upon looking into it over the weekend I can confirm that the command is not working.

Running `rly q txs cosmoshub "message.action=transfer"`

```
Error: RPC error -32603 - Internal error:
parse error near equal (line 1 symbol 16 - line 1 symbol 17):
"="
```

**Comment by boojamya** [comment]
Potentially removing this command in favor of having it implemented in `Lens`

**Comment by akc2267** [comment]
Lens is deprecated

**Comment by mmsqe** [comment]
query works with `rly q txs cosmoshub "message.action='/ibc.applications.transfer.v1.MsgTransfer'"`

**Comment by jtieri** [comment]
> query works with `rly q txs cosmoshub "message.action='/ibc.applications.transfer.v1.MsgTransfer'"`

thanks for verifying this, sounds like the original post was just a user related error then!

closing this issue out.
