### ISSUE TITLE
`rly tx relay-packets` bug

### ISSUE THREAD

**Issue by jtieri** [cosmos/relayer#960]
I noticed that there was a packet stuck on the axelar<->crescent path this morning, thanks to the monitoring in Axelar's Discord. I assumed that the running relayer instance somehow missed this packet and it became too far in the block history to be queried by the running instance so I attempted to run `rly tx relay-packets axelar-crescent channel-7  -d` but hit an error. I can confirm the stuck packet has a sequence of `7050 by running

```
rly q unrelayed-packets axelar-crescent channel-7
{"src":[7050],"dst":null}
```

But we see these logs on `rly tx relay-packets axelar-crescent channel-7  -d`

```
2022-08-29T16:24:17.828094Z	info	Failed to relay packet from sequence	{"src_chain_id": "axelar-dojo-1", "src_channel_id": "channel-7", "src_port_id": "transfer", "dst_chain_id": "crescent-1", "dst_channel_id": "channel-4", "dst_port_id": "transfer", "channel_order": "ORDER_UNORDERED", "error": "no ibc messages found for send_packet query: send_packet.packet_src_channel='channel-7' AND send_packet.packet_src_port='transfer' AND send_packet.packet_sequence='7050'"}
Error: no ibc messages found for send_packet query: send_packet.packet_src_channel='channel-7' AND send_packet.packet_src_port='transfer' AND send_packet.packet_sequence='7050'
```

**Comment by jtieri** [comment]
So far I haven't been able to replicate this issue. This occurred following an upgrade on Axelar iirc, so perhaps this was some weird edge case? Perhaps worth noting also is that multiple relayers failed to relay this one packet until manual intervention was taken.

**Comment by boojamya** [comment]
Just curious, do you know what they did to "un-stick" it?

**Comment by jtieri** [comment]
I need to double check on this but I think we may have ended up getting the packet relayed, after failing to relay the packet with this method i restarted the relayer instance using a huge block history so that the `ChainProcessor` would be forced to go back and observe the packet.

**Comment by jtieri** [comment]
Closing this issue for now due to not being able to reproduce the issue over the last week.
