### ISSUE TITLE
Strange behavior in simple querying command

### ISSUE THREAD

**Issue by georgelombardi97** [cosmos/relayer#972]
I have setup a relayer to osmosis testnet with this config.

```
{
  "type": "cosmos",
  "value": {
    "key": "test-1",
    "chain-id": "osmo-test-4",
    "rpc-addr": "https://osmosistest-rpc.quickapi.com:443",
    "account-prefix": "osmo",
    "keyring-backend": "test",
    "gas-adjustment": 2.0,
    "gas-prices": "0.025uosmo",
    "debug": true,
    "timeout": "300s",
    "output-format": "json",
    "sign-mode": "direct"
  }
}
```

I run a cli command and it works good ```rly q balance osmo-test-4 --home $CHAIN_DIR/$RELAYER_DIR``` 

In another terminal, I run `rly tx link [path] ...` and the relayer starts to try relaying.
Then In another cli I call the past command again: ```rly q balance osmo-test-4 --home $CHAIN_DIR/$RELAYER_DIR``` and it fails `error unmarshalling: invalid character '<' looking for beginning of value`

I kill the linking process and suddenly `q balance` works well. 

And also the same error is faced by relayer when trying to link:
`2022-09-05T10:39:13.308665Z	warn	Error querying block data	{"chain_name": "osmo-test-4", "chain_id": "osmo-test-4", "error": "error unmarshalling: invalid character '<' looking for beginning of value"}`

**Comment by georgelombardi97** [comment]
The issue was the rpc. url. I had tried all rpcs on chain registry and it didnt work. Someone else gave me an rpc and it worked well.

**Comment by ductrinhhuu** [comment]
could you please share testnet rpc for me and any1 who needs it? thank you in advance

**Comment by georgelombardi97** [comment]
> could you please share testnet rpc for me and any1 who needs it? thank you in advance

Check here:
https://github.com/cosmos/chain-registry/blob/master/cosmoshub/chain.json

But please note that most of the time public rpcs are almost useless because the relayer does A LOT of queries and the public rpcs usually ban you or have rate limits. So the best solution is to run your own node
