### ISSUE TITLE
Ethermint chains not compatible with rly

### ISSUE THREAD

**Issue by zdeadex** [cosmos/relayer#983]
Hello,

Tried to manage connection between chains like Injective, Evmos... using go relayer but it seems to oncounter RPC issues.
It is probably something related to the fact that they need something similar as Hermes configuration with the one line needed, for reminder:
`address_type = { derivation = 'ethermint', proto_type = { pk_type = '/injective.crypto.v1beta1.ethsecp256k1.PubKey' } }`

**Comment by boojamya** [comment]
I believe your issue is around using the `--coin-type` flag when creating or restoring your Evmos key. It should be coint-type 60.

We eventually plan to automatically pull this info from the chain-registry.

If this solution is unrelated, please re-open this issue.

**Comment by zdeadex** [comment]
@boojamya not about the key generation but rpc issue when trying to launch the relay

**Comment by jtieri** [comment]
Hey @zdeadex, can you confirm which version of the relayer you are using? Also, it may be beneficial to see your config as well as the command that you are using to initialize the relayer on startup. 

Going to re-open the issue for now as we discuss things further

**Comment by zdeadex** [comment]
@jtieri
```2022-10-03T23:19:09.974454Z     info    Failed to query clients {"chain_id": "injective-1", "attempt": 2, "max_attempts": 5, "error": "post failed: Post \"http://localhost:26657\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}```
Fact is, Injective doesn't have RPC support, so it doesn't work

Config below:
```    injective:
        type: cosmos
        value:
            key: relayer
            chain-id: injective-1
            rpc-addr: http://localhost:26657
            account-prefix: inj
            keyring-backend: test
            gas-adjustment: 1.2
            gas-prices: 0.01uinj
            debug: false
            timeout: 20s
            output-format: json
            sign-mode: direct
```

**Comment by jtieri** [comment]
I didn't get a version number in your response, but If you are running the relayer pre `v2.1.0` with just `rly start path_name` then these errors may be a result of the flaky legacy code used for relaying. `rly start path_name -p events` will utilize the newer event based relaying method which is much more performant, or you could use the most recently tagged release which does not need this explicit flag.

Regardless, I can say that there should be no RPC timeout issues running the relayer against an Injective node but there is a known issue regarding tx parsing. [lens](https://github.com/strangelove-ventures/lens) currently lacks support for the Injective account and msg types so the relayer never successfully relays packets against Injective. You end up seeing logs like this instead.

```
 Error building or broadcasting transaction      {"provider_type": "cosmos", "chain_id": "injective-888", "attempt": 2, "max_attempts": 5, "error": "rpc error: code = InvalidArgument desc = unable to resolve type URL /ethermint.crypto.v1.ethsecp256k1.PubKey: tx parse error: invalid request"}
 ```
 
 Evmos should work fine though. We tried following a similar pattern as https://github.com/strangelove-ventures/lens/pull/168 to add support for the Injective types but there seems to be some contention around the Injective SDK and the way they register the Amino codec types.

**Comment by zdeadex** [comment]
@jtieri version: 2.0.0-rc4

**Comment by zdeadex** [comment]
using 2.1.2 now having I think the "good" error:
```2022-10-04T05:09:03.750863Z     info    Failed to query clients {"chain_id": "injective-1", "attempt": 2, "max_attempts": 5, "error": "post failed: Post \"http://localhost:26657\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}```
